/**
 * Go Video Downloader
 *
 *    Copyright 2018 Tenta, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * For any questions, please contact developer@tenta.io
 *
 * masterregexp.go: Automatically generated regexp by combining URL validation expressions of all extractors
 */

// Code generated by transpiler. DO NOT EDIT.

package downloader

func init() {
	masterRegexps = []string{
		`(?:https?://(?:(?:(?:embed|www)\.)?acast\.com/|play\.acast\.com/s/)(?:[^/]+)/(?:` +
			`[^/#?]+))|(?:https?://tv\.adobe\.com/(?:(?:fr|de|es|jp)/)?watch/(?:[^/]+)/(?:[^/` +
			`]+))|(?:https?://video\.tv\.adobe\.com/v/(?:\d+))|(?:(?:aol-video:|https?://(?:(` +
			`?:www|on)\.)?aol\.com/(?:[^/]+/)*(?:[^/?#&]+-)?)(?:[^/?#&]+))|(?:https?://(?:www` +
			`\.)?allocine\.fr/(?:article|video|film)/(?:fichearticle_gen_carticle=|player_gen` +
			`_cmedia=|fichefilm_gen_cfilm=|video-)(?:[0-9]+)(?:\.html)?)|(?:https?://(?:www\.` +
			`)?aparat\.com/(?:v/|video/video/embed/videohash/)(?:[a-zA-Z0-9]+))|(?:^https?://` +
			`(?:(?:(?:www|classic)\.)?ardmediathek\.de|mediathek\.(?:daserste|rbb-online)\.de` +
			`|one\.ard\.de)/(?:.*/)(?:[0-9]+|[^0-9][^/\?]+)[^/\?]*(?:\?.*)?)|(?:https?://(?:w` +
			`ww\.)?audiomack\.com/song/(?:[\w/-]+))|(?:https?://[^/]+\.bandcamp\.com/track/(?` +
			`:[^/?#&]+))|(?:https?://(?:www\.)?bandcamp\.com/?\?(?:.*?&)?show=(?:\d+))|(?:htt` +
			`ps?://(?:www\.)?beeg\.com/(?:\d+))|(?:https?://(?:www\.|pro\.)?beatport\.com/tra` +
			`ck/(?:[^/]+)/(?:[0-9]+))|(?:https?://(?:www\.)?bigflix\.com/.+/(?:[0-9]+))|(?:ht` +
			`tps?://(?:www\.)?bild\.de/(?:[^/]+/)+(?:[^/]+)-(?:\d+)(?:,auto=true)?\.bild\.htm` +
			`l)|(?:https?://(?:www\.)?bitchute\.com/(?:video|embed|torrent/[^/]+)/(?:[^/?#&]+` +
			`))|(?:https?://(?:www\.)?bleacherreport\.com/video_embed\?id=(?:[0-9a-f-]{36}))|` +
			`(?:https?://(?:www\.)?bpb\.de/mediathek/(?:[0-9]+)/)|(?:(?:https?://.*brightcove` +
			`\.com/(services|viewer).*?\?|brightcove:)(?:.*))|(?:https?://players\.brightcove` +
			`\.net/(?:\d+)/(?:[^/]+)_(?:[^/]+)/index\.html\?.*videoId=(?:\d+|ref:[^&]+))|(?:h` +
			`ttps?://(?:[^/]+\.)?businessinsider\.(?:com|nl)/(?:[^/]+/)*(?:[^/?#&]+))|(?:http` +
			`s?://(?:www\.)?camdemy\.com/media/(?:\d+))|(?:https?://(?:www\.)?(?:mycanal|piwi` +
			`plus)\.fr/(?:[^/]+/)*(?:[^?/]+)(?:\.html\?.*\bvid=|/p/)(?:\d+))|(?:https?://(?:(` +
			`?:www\.)?canalc2\.tv/video/|archives-canalc2\.u-strasbg\.fr/video\.asp\?.*\bidVi` +
			`deo=)(?:\d+))|(?:https?://(?:www\.)?media\.ccc\.de/v/(?:[^/?#&]+))|(?:https?://(` +
			`?:www\.)?charlierose\.com/(?:video|episode)(?:s|/player)/(?:\d+))|(?:https?://(?` +
			`:www\.)?chirb\.it/(?:(?:wp|pl)/|fb_chirbit_player\.swf\?key=)?(?:[\da-zA-Z]+))|(` +
			`?:https?://player\.cinchcast\.com/.*?(?:assetId|show_id)=(?:[0-9]+))|(?:https?:/` +
			`/(?:www\.)?clippituser\.tv/c/(?:[a-z]+))|(?:https?://(?:chic|www)\.clipsyndicate` +
			`\.com/video/play(list/\d+)?/(?:\d+))|(?:https?://(?:www\.)?clyp\.it/(?:[a-z0-9]+` +
			`))|(?:https?://(?:(?:edition|www|money)\.)?cnn\.com/(?:video/(?:data/.+?|\?)/)?v` +
			`ideos?/(?:.+?/(?:[^/]+?)(?:\.(?:[a-z\-]+)|(?=&))))|(?:(?:coub:|https?://(?:coub\` +
			`.com/(?:view|embed|coubs)/|c-cdn\.coub\.com/fb-player\.swf\?.*\bcoub(?:ID|id)=))` +
			`(?:[\da-z]+))|(?:https?://(?:www\.)?cracked\.com/video_(?:\d+)_[\da-z-]+\.html)|` +
			`(?:https?://(?:www\.)?c-span\.org/video/\?(?:[0-9a-f]+))|(?:https?://news\.cts\.` +
			`com\.tw/[a-z]+/[a-z]+/\d+/(?:\d+)\.html)|(?:https?://(?:app\.)?curiositystream\.` +
			`com/video/(?:\d+))|(?:https?://(?:www\.)?dailymail\.co\.uk/(?:video/[^/]+/video-` +
			`|embed/video/)(?:[0-9]+))|(?:(?i)https?://(?:(www|touch)\.)?dailymotion\.[a-z]{2` +
			`,3}/(?:(?:(?:embed|swf|#)/)?video|swf)/(?:[^/?_]+))|(?:https?://(?:www\.)?digg\.` +
			`com/video/(?:[^/?#&]+))|(?:https?://(?:www\.)?dotsub\.com/view/(?:[^/]+))|(?:htt` +
			`ps?://(?:www\.)?(?:discovery|tlc|animalplanet|dmax)\.de/(?:.*\#(?:\d+)|(?:[^/]+/` +
			`)*videos/(?:[^/?#]+)|programme/(?:[^/]+)/video/(?:[^/]+)))|(?:https?://(?:(?:[^/` +
			`]+\.)?(?:disney\.[a-z]{2,3}(?:\.[a-z]{2})?|disney(?:(?:me|latino)\.com|turkiye\.` +
			`com\.tr|channel\.de)|(?:starwars|marvelkids)\.com))/(?:(?:embed/|(?:[^/]+/)+[\w-` +
			`]+-)(?:[a-z0-9]{24})|(?:[^/]+/)?(?:[^/?#]+)))|(?:https?://(?:s?evt\.dispeak|even` +
			`ts\.digitallyspeaking)\.com/(?:[^/]+/)+xml/(?:[^.]+)\.xml)|(?:https?://(?:www\.)` +
			`?dw\.com/(?:[^/]+/)+(?:av|e)-(?:\d+))|(?:https?://(?:www\.)?ebaumsworld\.com/vid` +
			`eos/[^/]+/(?:\d+))|(?:https?://(?:www\.)?echo\.msk\.ru/sounds/(?:\d+))|(?:https?` +
			`://(?:[^.]+\.)?elpais\.com/.*/(?:[^/#?]+)\.html(?:$|[?#]))|(?:https?://(?:www\.)` +
			`?engadget\.com/video/(?:[^/?#]+))|(?:https?://ec\.europa\.eu/avservices/(?:video` +
			`/player|audio/audioDetails)\.cfm\?.*?\bref=(?:[A-Za-z0-9-]+))|(?:https?://(?:www` +
			`\.)?extremetube\.com/(?:[^/]+/)?video/(?:[^/#?&]+))|(?:(?:https?://(?:[\w-]+\.)?` +
			`(?:facebook\.com|facebookcorewwwi\.onion)/(?:[^#]*?\#!/)?(?:(?:video/video\.php|` +
			`photo\.php|video\.php|video/embed|story\.php)\?(?:.*?)(?:v|video_id|story_fbid)=` +
			`|[^/]+/videos/(?:[^/]+/)?|[^/]+/posts/|groups/[^/]+/permalink/)|facebook:)(?:[0-` +
			`9]+))|(?:https?://(?:[\w-]+\.)?facebook\.com/plugins/video\.php\?.*?\bhref=(?:ht` +
			`tps.+))|(?:https?://(?:www\.)?faz\.net/(?:[^/]+/)*.*?-(?:\d+)\.html)|(?:(?:5min:` +
			`|https?://(?:[^/]*?5min\.com/|delivery\.vidible\.tv/aol)(?:(?:Scripts/PlayerSeed` +
			`\.js|playerseed/?)?\?.*?playList=)?)(?:\d+))|(?:https?://(?:www\.)?franceculture` +
			`\.fr/emissions/(?:[^/]+/)*(?:[^/?#&]+))|(?:https?://(?:www\.)?freesound\.org/peo` +
			`ple/[^/]+/sounds/(?:[^/]+))|(?:https?://(?:www\.)?gamespot\.com/(?:video|article` +
			`|review)s/(?:[^/]+/\d+-|embed/)(?:\d+))|(?:https?://(?:www\.)?gaskrank\.tv/tv/(?` +
			`:[^/]+)/(?:[^/]+)\.htm)|(?:https?://(?:www\.)?gdcvault\.com/play/(?:\d+)/(?:(\w|` +
			`-)+)?)|(?:https?://(?:www\.)?gfycat\.com/(?:ifr/|gifs/detail/)?(?:[^/?#]+))|(?:h` +
			`ttps?://(?:www\.)?godtube\.com/watch/\?v=(?:[\da-zA-Z]+))|(?:^https?://video\.go` +
			`lem\.de/.+?/(?:.+?)/)|(?:https?://on-demand\.gputechconf\.com/gtc/2015/video/S(?` +
			`:\d+)\.html)|(?:https?://(?:www\.)?historicfilms\.com/(?:tapes/|play)(?:\d+))|(?` +
			`:https?://(?:www\.)?hitrecord\.org/records/(?:\d+))|(?:http?://(?:www\.)?hornbun` +
			`ny\.com/videos/(?:[a-z-]+)-(?:\d+)\.html)|(?:https?://[\da-z-]+\.(?:howstuffwork` +
			`s|stuff(?:(?:youshould|theydontwantyouto)know|toblowyourmind|momnevertoldyou)|(?` +
			`:brain|car)stuffshow|fwthinking|geniusstuff)\.com/(?:[^/]+/)*(?:\d+-)?(?:.+?)-vi` +
			`deo\.htm)|(?:https?://(?:www|m)\.imdb\.com/(?:video|title|list).+?[/-]vi(?:\d+))` +
			`|(?:https?://(?:i\.)?imgur\.com/(?!(?:a|gallery|(?:t(?:opic)?|r)/[^/]+)/)(?:[a-z` +
			`A-Z0-9]+))|(?:https?://(?:i\.)?imgur\.com/(?:gallery|(?:t(?:opic)?|r)/[^/]+)/(?:` +
			`[a-zA-Z0-9]+))|(?:https?://(?:www\.)?ina\.fr/video/(?:I?[A-Z0-9]+))|(?:https?://` +
			`(?:www\.)?infoq\.com/(?:[^/]+/)+(?:[^/]+))|(?:(?:https?://(?:www\.)?instagram\.c` +
			`om/p/(?:[^/?#&]+)))|(?:https?://(?:www\.)?90tv\.ir/video/(?:[0-9]+)/.*)|(?:https` +
			`?://(?:www\.)?ivideon\.com/tv/(?:[^/]+/)*camera/(?:\d+-[\da-f]+)/(?:\d+))|(?:htt` +
			`ps?://(?:(?:www|m)\.)?izlesene\.com/(?:video|embedplayer)/(?:[^/]+/)?(?:[0-9]+))` +
			`|(?:https?://(?:licensing\.jamendo\.com/[^/]+|(?:www\.)?jamendo\.com)/track/(?:[` +
			`0-9]+)/(?:[^/?#&]+))|(?:https?://.*?\.jeuxvideo\.com/.*/(.*?)\.htm)|(?:(?:joj:|h` +
			`ttps?://media\.joj\.sk/embed/)(?:[^/?#^]+))|(?:(?:https?://(?:content\.jwplatfor` +
			`m|cdn\.jwplayer)\.com/(?:(?:feed|player|thumb|preview|video|manifest)s|jw6|v2/me` +
			`dia)/|jwplatform:)(?:[a-zA-Z0-9]{8}))|(?:https?://(?:www\.)?keezmovies\.com/vide` +
			`o/(?:(?:[^/]+)-)?(?:\d+))|(?:https?://(?:www\.)?kickstarter\.com/projects/(?:[^/` +
			`]*)/.*)|(?:https?://krasview\.ru/(?:video|embed)/(?:\d+))|(?:https?://(?:www\.)?` +
			`lci\.fr/[^/]+/[\w-]+-(?:\d+)\.html)|(?:https?://(?:www\.)?loc\.gov/(?:item/|toda` +
			`y/cyberlc/feature_wdesc\.php\?.*\brec=)(?:[0-9a-z_.]+))|(?:(?:https?://html5-pla` +
			`yer\.libsyn\.com/embed/episode/id/(?:[0-9]+)))|(?:(?:limelight:media:|https?://(` +
			`?:link\.videoplatform\.limelight\.com/media/|assets\.delvenetworks\.com/player/l` +
			`oader\.swf)\?.*?\bmediaId=)(?:[a-z0-9]{32}))|(?:https?://(?:new\.)?livestream\.c` +
			`om/(?:accounts/(?:\d+)|(?:[^/]+))/(?:events/(?:\d+)|(?:[^/]+))(?:/videos/(?:\d+)` +
			`)?)|(?:https?://(?:www\.)?lovehomeporn\.com/video/(?:\d+)(?:/(?:[^/?#&]+))?)|(?:` +
			`https?://(?:www\.)?macgamestore\.com/mediaviewer\.php\?trailer=(?:\d+))|(?:(?i)h` +
			`ttps?://(?:www\.)?manyvids\.com/video/(?:\d+))|(?:https?://(?:www\.)?massengesch` +
			`mack\.tv/play/(?:[^?&#]+))|(?:https://player\.megaphone\.fm/(?:[A-Z0-9]+))|(?:ht` +
			`tps?://(?:www\.)?metacritic\.com/.+?/trailers/(?:\d+))|(?:(?:mva:|https?://(?:mv` +
			`a\.microsoft|(?:www\.)?microsoftvirtualacademy)\.com/[^/]+/training-courses/[^/?` +
			`#&]+-)(?:\d+)(?::|\?l=)(?:[\da-zA-Z]+_\d+))|(?:https?://(?:[\da-z_-]+\.)*(?:mlb)` +
			`\.com/(?:(?:(?:[^/]+/)*c-|(?:shared/video/embed/(?:embed|m-internal-embed)\.html` +
			`|(?:[^/]+/)+(?:play|index)\.jsp|)\?.*?\bcontent_id=)(?:\d+)))|(?:https?://(?:www` +
			`\.)?mofosex\.com/videos/(?:\d+)/(?:[^/?#&.]+)\.html)|(?:https?://(?:www\.)?mojvi` +
			`deo\.com/video-(?:[^/]+)/(?:[a-f0-9]+))|(?:https?://myspace\.com/[^/]+/(?:video/` +
			`[^/]+/(?:\d+)|music/song/[^/?#&]+-(?:\d+)-\d+(?:[/?#&]|$)))|(?:(?:https?://(?:ww` +
			`w\.)?myvi\.(?:(?:ru/player|tv)/(?:(?:embed/html|flash|api/Video/Get)/|content/pr` +
			`eloader\.swf\?.*\bid=)|ru/watch/)|myvi:)(?:[\da-zA-Z_-]+))|(?:https?://(?:www\.)` +
			`?ndr\.de/(?:[^/]+/)*(?:[^/?#]+),[\da-z]+\.html)|(?:https?://(?:www\.)?ndr\.de/(?` +
			`:[^/]+/)*(?:[\da-z]+)-(?:player|externalPlayer)\.html)|(?:https?://(?:www\.)?n-j` +
			`oy\.de/(?:[^/]+/)*(?:[\da-z]+)-(?:player|externalPlayer)_[^/]+\.html)|(?:https?:` +
			`//(?:[^/]+\.)?ndtv\.com/(?:[^/]+/)*videos?/?(?:[^/]+/)*[^/?^&]+-(?:\d+))|(?:http` +
			`s?://(?:www\.)?netzkino\.de/\#!/(?:[^/]+)/(?:[^/]+))|(?:https?://(?:www\.)?newgr` +
			`ounds\.com/(?:audio/listen|portal/view)/(?:[0-9]+))|(?:https?://(?:www\.)?nexttv` +
			`\.com\.tw/(?:[^/]+/)+(?:\d+))|(?:(?:https?://api\.nexx(?:\.cloud|cdn\.com)/v3/(?` +
			`:\d+)/videos/byid/|nexx:(?:(?:\d+):)?|https?://arc\.nexx\.cloud/api/video/)(?:\d` +
			`+))|(?:https?://(?:www\.)?(?:nhl|wch2016)\.com/(?:[^/]+/)*c-(?:\d+))|(?:https?:/` +
			`/media\.cms\.nova\.cz/embed/(?:[^/?#&]+))|(?:https?://(?:(?:www|cn)\.)?nowness\.` +
			`com/(?:story|(?:series|category)/[^/]+)/(?:[^/]+?)(?:$|[?#]))|(?:https?://(?:www` +
			`\.)?ntv\.ru/(?:[^/]+/)*(?:[^/?#&]+))|(?:https?://(?:(?:www|m|mobile)\.)?(?:odnok` +
			`lassniki|ok)\.ru/(?:video(?:embed)?/|web-api/video/moviePlayer/|live/|dk\?.*?st\` +
			`.mvId=)(?:[\d-]+))|(?:(?:ooyala:|https?://.+?\.ooyala\.com/.*?(?:embedCode|ec)=)` +
			`(?:.+?)(&|$))|(?:https?://(?:www\.)?outsidetv\.com/(?:[^/]+/)*?play/[a-zA-Z0-9]{` +
			`8}/\d+/\d+/(?:[a-zA-Z0-9]{8}))|(?:https?://(?:(?:www\.)?packtpub\.com/mapt|subsc` +
			`ription\.packtpub\.com)/video/[^/]+/(?:\d+)/(?:\d+)/(?:\d+))|(?:https?://(?:(?:w` +
			`ww\.)?pandora\.tv/view/(?:[^/]+)/(?:\d+)|(?:.+?\.)?channel\.pandora\.tv/channel/` +
			`video\.ptv\?|m\.pandora\.tv/?\?))|(?:https?://(?:www\.)?patreon\.com/(?:creation` +
			`\?hid=|posts/(?:[\w-]+-)?)(?:\d+))|(?:https?://(?:www\.)?pearvideo\.com/video_(?` +
			`:\d+))|(?:https?://(?:www\.)?people\.com/people/videos/0,,(?:\d+),00\.html)|(?:h` +
			`ttps?://(?:[a-z0-9]+\.)?photobucket\.com/.*(([\?\&]current=)|_)(?:.*)\.(?:(flv)|` +
			`(mp4)))|(?:https?://(?:www\.)?play\.fm/(?:(?:[^/]+/)+(?:[^/]+))/?(?:$|[?#]))|(?:` +
			`https?://(?:www\.)?plays\.tv/(?:video|embeds)/(?:[0-9a-f]{18}))|(?:https?://(?:w` +
			`ww\.)?playvid\.com/watch(\?v=|/)(?:.+?)(?:#|$))|(?:(?:https?)://(?:(?:[^.]+)\.po` +
			`domatic\.com/entry|(?:www\.)?podomatic\.com/podcasts/(?:[^/]+)/episodes)/(?:[^/?` +
			`#&]+))|(?:https?://(?:www\.)?pokemon\.com/[a-z]{2}(?:.*?play=(?:[a-z0-9]{32})|/(` +
			`?:[^/]+/)+(?:[^/?#&]+)))|(?:(?:https?://)(?:www\.|)91porn\.com/.+?\?viewkey=(?:[` +
			`\w\d]+))|(?:https?://(?:[a-zA-Z]+\.)?porn\.com/videos/(?:(?:[^/]+)-)?(?:\d+))|(?` +
			`:https?://(?:www\.)?pornhd\.com/(?:[a-z]{2,4}/)?videos/(?:\d+)(?:/(?:.+))?)|(?:h` +
			`ttps?://(?:(?:[^/]+\.)?(?:pornhub\.(?:com|net))/(?:(?:view_video\.php|video/show` +
			`)\?viewkey=|embed/)|(?:www\.)?thumbzilla\.com/video/)(?:[\da-z]+))|(?:https?://(` +
			`?:\w+\.)?pornotube\.com/(?:[^?#]*?)/video/(?:[0-9]+))|(?:https?://(?:www\.)?puhu` +
			`tv\.com/(?:[^/?#&]+)-izle)|(?:https?://(?:www\.)?presstv\.ir/[^/]+/(?:\d+)/(?:\d` +
			`+)/(?:\d+)/(?:\d+)/(?:[^/]+)?)|(?:https?://(?:.+?)\.(?:radio\.(?:de|at|fr|pt|es|` +
			`pl|it)|rad\.io))|(?:https?://(?:www\.)?radiojavan\.com/videos/video/(?:[^/]+)/?)` +
			`|(?:https?://[^/]+\.(?:rai\.(?:it|tv)|rainews\.it)/.+?-(?:[\da-f]{8}-[\da-f]{4}-` +
			`[\da-f]{4}-[\da-f]{4}-[\da-f]{12})(?:-.+?)?\.html)|(?:https?://(?:videos\.raywen` +
			`derlich\.com/courses|(?:www\.)?raywenderlich\.com)/(?:[^/]+)/lessons/(?:\d+))|(?` +
			`:https?://(?:www\.)?(?:rbmaradio|redbullradio)\.com/shows/(?:[^/]+)/episodes/(?:` +
			`[^/?#&]+))|(?:https?://(?:(?:www\.)?redtube\.com/|embed\.redtube\.com/\?.*?\bid=` +
			`)(?:[0-9]+))|(?:(?:rentv:|https?://(?:www\.)?ren\.tv/(?:player|video/epizod)/)(?` +
			`:\d+))|(?:^https?://(?:www\.)?reverbnation\.com/.*?/song/(?:\d+).*?$)|(?:https?:` +
			`//(?:www\.)?rockstargames\.com/videos(?:/video/|#?/?\?.*\bvideo=)(?:\d+))|(?:htt` +
			`ps?://(?:www\.)?prehravac\.rozhlas\.cz/audio/(?:[0-9]+))|(?:rts:(?:\d+)|https?:/` +
			`/(?:.+?\.)?rts\.ch/(?:[^/]+/){2,}(?:[0-9]+)-(?:.+?)\.html)|(?:https?://(?:www\.)` +
			`?rtvs\.sk/(?:radio|televizia)/archiv/\d+/(?:\d+))|(?:https?://(?:test)?player\.(` +
			`?:rutv\.ru|vgtrk\.com)/(?:flash\d+v/container\.swf\?id=|iframe/(?:swf|video|live` +
			`)/id/|index/iframe/cast_id/)(?:\d+))|(?:https?://(?:(?:v2|www)\.)?videos\.sapo\.` +
			`(?:pt|cv|ao|mz|tl)/(?:[\da-zA-Z]{20}))|(?:https?://(?:www\.)?screencast\.com/t/(` +
			`?:[a-zA-Z0-9]+))|(?:https?://(?:www\.)?senate\.gov/isvp/?\?(?:.+))|(?:https?://(` +
			`?:www\.)?seznamzpravy\.cz/iframe/player\?.*\bsrc=)|(?:https?://(?:www\.)?slidesh` +
			`are\.net/[^/]+?/(?:.+?)($|\?))|(?:https?://(?:\w+\.)?slutload\.com/(?:video/[^/]` +
			`+|embed_player|watch)/(?:[^/]+))|(?:https?://(?:www\.)?soundgasm\.net/u/(?:[0-9a` +
			`-zA-Z_-]+)/(?:[0-9a-zA-Z_-]+))|(?:https?://(?:www\.)?stitcher\.com/podcast/(?:[^` +
			`/]+/)+e/(?:(?:[^/#?&]+?)-)?(?:\d+)(?:[/#?&]|$))|(?:https?://openclassroom\.stanf` +
			`ord\.edu(?:/?|(/MainFolder/(?:HomePage|CoursePage|VideoPage)\.php([?]course=(?:[` +
			`^&]+)(&video=(?:[^&]+))?(&.*)?)?))$)|(?:https?://streamable\.com/(?:[es]/)?(?:\w` +
			`+))|(?:https?://(?:(?:www\.)?sunporno\.com/videos|embeds\.sunporno\.com/embed)/(` +
			`?:\d+))|(?:https?://(?:www\.)?swrmediathek\.de/(?:content/)?player\.htm\?show=(?` +
			`:[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}))|(?:https?://(?:www\.)` +
			`?tagesschau\.de/(?:[^/]+/(?:[^/]+/)*?(?:[^/#?]+?(?:-?[0-9]+)?))(?:~_?[^/#?]+?)?\` +
			`.html)|(?:https?://(?:www\.)?tastytrade\.com/tt/shows/[^/]+/episodes/(?:[^/?#&]+` +
			`))|(?:https?://tds\.lifeway\.com/v1/trainingdeliverysystem/courses/(?:\d+)/index` +
			`\.html)|(?:https?://(?:www\.)?teachertube\.com/(viewVideo\.php\?video_id=|music\` +
			`.php\?music_id=|video/(?:[\da-z-]+-)?|audio/)(?:\d+))|(?:(?:https?://)(?:www|emb` +
			`ed(?:-ssl)?)(?:\.ted\.com/((?:playlists(?:/\d+)?)|((?:talks))|(?:watch)/[^/]+/[^` +
			`/]+)(/lang/(.*?))?/(?:[\w-]+).*)$)|(?:^https?://(?:www\.)?t13\.cl/videos(?:/[^/]` +
			`+)+/(?:[\w-]+))|(?:https?://(?:www\.)?tenta\.com/how-to-download-videos)|(?:http` +
			`s?://(?:www\.)?thisoldhouse\.com/(?:watch|how-to|tv-episode)/(?:[^/?#]+))|(?:htt` +
			`ps?://(?:m\.)?tiktok\.com/v/(?:\d+))|(?:https?://(?:.+?\.)?tinypic\.com/player\.` +
			`php\?v=(?:[^&]+)&s=\d+)|(?:https?://player\.(?:tna|emp)flix\.com/video/(?:\d+))|` +
			`(?:https?://(?:www\.)?tnaflix\.com/[^/]+/(?:[^/]+)/video(?:\d+))|(?:https?://(?:` +
			`www\.)?empflix\.com/(?:videos/(?:.+?)-|[^/]+/(?:[^/]+)/video)(?:[0-9]+))|(?:http` +
			`s?://(?:www\.)?moviefap\.com/videos/(?:[0-9a-f]+)/(?:[^/]+)\.html)|(?:https?://v` +
			`ideos\.toypics\.net/view/(?:[0-9]+))|(?:https?://(?:(?:www|m)\.)?trilulilu\.ro/(` +
			`?:[^/]+/)?(?:[^/#\?]+))|(?:https?://(?:www\.)?tube8\.com/(?:[^/]+/)+(?:[^/]+)/(?` +
			`:\d+))|(?:https?://(?:[^/?#&]+)\.tumblr\.com/(?:post|video)/(?:[0-9]+)(?:$|[/?#]` +
			`))|(?:https?://(?:(?:www\.)?tune\.pk/(?:video/|player/embed_player.php?.*?\bvid=` +
			`)|embed\.tune\.pk/play/)(?:\d+))|(?:https?://(?:www\.)?tvanouvelles\.ca/videos/(` +
			`?:\d+))|(?:https?://(?:www\.)?tvc\.ru/video/iframe/id/(?:\d+))|(?:https?://(?:ww` +
			`w\.)?tvc\.ru/(?!video/iframe/id/)(?:[^?#]+))|(?:https?://(?:(?:[^/]+)\.)?tvn24(?` +
			`:bis)?\.pl/(?:[^/]+/)*(?:[^/]+))|(?:(?:tvp:|https?://[^/]+\.tvp\.(?:pl|info)/ses` +
			`s/tvplayer\.php\?.*?object_id=)(?:\d+))|(?:https?://[^/]+\.tvp\.(?:pl|info)/(?:v` +
			`ideo/(?:[^,\s]*,)*|(?:(?!\d+/)[^/]+/)*)(?:\d+))|(?:https?://tvplay\.(?:tv3\.lt|s` +
			`katies\.lv|tv3\.ee)/[^/]+/[^/?#&]+-(?:\d+))|(?:https?://(?:www\.)?20min\.ch/(?:v` +
			`ideotv/*\?.*?\bvid=|videoplayer/videoplayer\.html\?.*?\bvideoId@)(?:\d+))|(?:htt` +
			`ps?://(?:clips\.twitch\.tv/(?:[^/]+/)*|(?:www\.)?twitch\.tv/[^/]+/clip/)(?:[^/?#` +
			`&]+))|(?:https?://amp\.twimg\.com/v/(?:[0-9a-f\-]{36}))|(?:https?://(?:www\.)?(?` +
			`:digiteka\.net|ultimedia\.com)/(?:deliver/(?:generic|musique)(?:/[^/]+)*/(?:src|` +
			`article)|default/index/video(?:generic|music)/id)/(?:[\d+a-z]+))|(?:https?://utv` +
			`\.unistra\.fr/(?:index|video)\.php\?id_video\=(?:\d+))|(?:https?://(?:.+?\.)?uol` +
			`\.com\.br/.*?(?:(?:mediaId|v)=|view/(?:[a-z0-9]+/)?|video(?:=|/(?:\d{4}/\d{2}/\d` +
			`{2}/)?))(?:\d+|[\w-]+-[A-Z0-9]+))|(?:https?://(?:www\.)?usatoday\.com/(?:[^/]+/)` +
			`*(?:[^?/#]+))|(?:https?://(?:(?:app|embed)\.)?ustudio\.com/embed/(?:[^/]+)/(?:[^` +
			`/]+))|(?:https?://(?:www\.)?video\.varzesh3\.com/(?:[^/]+/)+(?:[^/]+)/?)|(?:http` +
			`s?://(?:[^/]+\.)?vbox7\.com/(?:play:|(?:emb/external\.php|player/ext\.swf)\?.*?\` +
			`bvid=)(?:[\da-fA-F]+))|(?:https?://veehd\.com/video/(?:\d+))|(?:https?://(?:.+?\` +
			`.)?vesti\.ru/(?:.+))|(?:(?:https?://(?:www\.)?vevo\.com/watch/(?!playlist|genre)` +
			`(?:[^/]+/(?:[^/]+/)?)?|https?://cache\.vevo\.com/m/html/embed\.html\?video=|http` +
			`s?://videoplayer\.vevo\.com/embed/embedded\?videoId=|vevo:)(?:[^&?#]+))|(?:https` +
			`?://(?:www\.)?viddler\.com/(?:v|embed|player)/(?:[a-z0-9]+))|(?:https?://videopr` +
			`ess\.com/embed/(?:[\da-zA-Z]+))|(?:https?://(?:www\.|m\.|)videosz\.com/[a-z]+/[a` +
			`-z]+/(?:[0-9]+)_)|(?:https?://(?:www\.)?vidlii\.com/(?:watch|embed)\?.*?\bv=(?:[` +
			`0-9A-Za-z_-]{11}))|(?:https?://(?:(?:www|(?:player))\.)?vimeo(?:pro)?\.com/(?!(?` +
			`:channels|album)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)(?:.*?/)?(?:(?:play` +
			`_redirect_hls|moogaloop\.swf)\?clip_id=)?(?:videos?/)?(?:[0-9]+)(?:/[\da-f]+)?/?` +
			`(?:[?&].*)?(?:[#].*)?$)|(?:https?://(?:www\.)?vimeo\.com/ondemand/(?:[^/?#&]+))|` +
			`(?:https?://(?:player\.vimple\.(?:ru|co)/iframe|vimple\.(?:ru|co))/(?:[\da-f-]{3` +
			`2,36}))|(?:https?://(?:www\.)?vine\.co/(?:v|oembed)/(?:\w+))|(?:(?:viqeo:|https?` +
			`://cdn\.viqeo\.tv/embed/*\?.*?\bvid=|https?://api\.viqeo\.tv/v\d+/data/startup?.` +
			`*?\bvideo(?:%5B%5D|\[\])=)(?:[\da-f]+))|(?:https?://(?:(?:(?:(?:m|new)\.)?vk\.co` +
			`m/video_|(?:www\.)?daxab.com/)ext\.php\?(?:.*?\boid=(?:-?\d+).*?\bid=(?:\d+).*)|` +
			`(?:(?:(?:m|new)\.)?vk\.com/(?:.+?\?.*?z=)?video|(?:www\.)?daxab.com/embed/)(?:-?` +
			`\d+_\d+)(?:.*\blist=(?:[\da-f]+))?))|(?:https?://(?:(?:www|m)\.)?vlive\.tv/video` +
			`/(?:[0-9]+))|(?:https?://(?:m\.)?vuclip\.com/w\?.*?cid=(?:[0-9]+))|(?:https?://(` +
			`?:(?:www|view)\.)?vzaar\.com/(?:videos/)?(?:\d+))|(?:(?:washingtonpost:|https?:/` +
			`/(?:www\.)?washingtonpost\.com/video/(?:[^/]+/)*)(?:[\da-f]{8}-[\da-f]{4}-[\da-f` +
			`]{4}-[\da-f]{4}-[\da-f]{12}))|(?:(?:wat:|https?://(?:www\.)?wat\.tv/video/.*-)(?` +
			`:[0-9a-z]+))|(?:https?://m\.weibo\.cn/status/(?:[0-9]+)(\?.+)?)|(?:https?://(?:w` +
			`ww|m)\.worldstar(?:candy|hiphop)\.com/(?:videos|android)/video\.php\?.*?\bv=(?:[` +
			`^&]+))|(?:https?://(?:.+?\.)?xhamster\.com/(?:movies/(?:\d+)/(?:[^/]*)\.html|vid` +
			`eos/(?:[^/]*)-(?:\d+)))|(?:https?://(?:.+?\.)?xhamster\.com/xembed\.php\?video=(` +
			`?:\d+))|(?:https?://(?:video|www)\.xnxx\.com/video-?(?:[0-9a-z]+)/)|(?:(?:xtube:` +
			`|https?://(?:www\.)?xtube\.com/(?:watch\.php\?.*\bv=|video-watch/(?:embedded/)?(` +
			`?:[^/]+)-))(?:[^/?&#]+))|(?:https?://(?:(?:www\.)?xvideos\.com/video|flashservic` +
			`e\.xvideos\.com/embedframe/|static-hw\.xvideos\.com/swf/xv-player\.swf\?.*?\bid_` +
			`video=)(?:[0-9]+))|(?:https?://(?:www\.)?xxxymovies\.com/videos/(?:\d+)/(?:[^/]+` +
			`))|(?:https?://v\.yinyuetai\.com/video(?:/h5)?/(?:[0-9]+))|(?:https?://(?:\w+\.)` +
			`?youjizz\.com/videos/(?:[^/#?]*-(?:\d+)\.html|embed/(?:\d+)))|(?:https?://(?:www` +
			`\.)?youporn\.com/watch/(?:\d+)/(?:[^/?#&]+))|(?:https?://(?:www\.)?yourporn\.sex` +
			`y/post/(?:[^/?#&.]+))|(?:https?://(?:www\.)?(?:yourupload\.com/(?:watch|embed)|e` +
			`mbed\.yourupload\.com)/(?:[A-Za-z0-9]+))|(?:^((?:https?://|//)(?:(?:(?:(?:\w+\.)` +
			`?[yY][oO][uU][tT][uU][bB][eE](?:-nocookie)?\.com/|(?:www\.)?deturl\.com/www\.you` +
			`tube\.com/|(?:www\.)?pwnyoutube\.com/|(?:www\.)?hooktube\.com/|(?:www\.)?yourepe` +
			`at\.com/|tube\.majestyc\.net/|(?:www\.)?invidio\.us/|youtube\.googleapis\.com/)(` +
			`?:.*?\#/)?(?:(?:(?:v|embed|e)/(?!videoseries))|(?:(?:(?:watch|movie)(?:_popup)?(` +
			`?:\.php)?/?)?(?:\?|\#!?)(?:.*?[&;])??v=)))|(?:youtu\.be|vid\.plus|zwearz\.com/wa` +
			`tch|)/|(?:www\.)?cleanvideosearch\.com/media/action/yt/watch\?videoId=))?([0-9A-` +
			`Za-z_-]{11})(?!.*?\blist=(?:(?:PL|LL|EC|UU|FL|RD|UL|TL)[0-9A-Za-z-_]{10,}|WL))$)`,
	}
}
