/**
 * Go Video Downloader
 *
 *    Copyright 2018 Tenta, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * For any questions, please contact developer@tenta.io
 *
 * masterregexp.go: Automatically generated regexp by combining URL validation expressions of all extractors
 */

// Code generated by transpiler. DO NOT EDIT.

package downloader

func init() {
	masterRegexps = []string{
		`(?:https?://abcnews\.go\.com/(?:[^/]+/video/(?:[0-9a-z-]+)-|video/embed\?.*?\bid` +
			`=)(?:\d+))|(?:https?://(?:(?:(?:embed|www)\.)?acast\.com/|play\.acast\.com/s/)(?` +
			`:[^/]+)/(?:[^/#?]+))|(?:https?://tv\.adobe\.com/(?:(?:fr|de|es|jp)/)?watch/(?:[^` +
			`/]+)/(?:[^/]+))|(?:https?://video\.tv\.adobe\.com/v/(?:\d+))|(?:(?:aol-video:|ht` +
			`tps?://(?:(?:www|on)\.)?aol\.com/(?:[^/]+/)*(?:[^/?#&]+-)?)(?:[^/?#&]+))|(?:http` +
			`s?://(?:www\.)?allocine\.fr/(?:article|video|film)/(?:fichearticle_gen_carticle=` +
			`|player_gen_cmedia=|fichefilm_gen_cfilm=|video-)(?:[0-9]+)(?:\.html)?)|(?:https?` +
			`://(?:www\.)?aparat\.com/(?:v/|video/video/embed/videohash/)(?:[a-zA-Z0-9]+))|(?` +
			`:^https?://(?:(?:(?:www|classic)\.)?ardmediathek\.de|mediathek\.(?:daserste|rbb-` +
			`online)\.de|one\.ard\.de)/(?:.*/)(?:[0-9]+|[^0-9][^/\?]+)[^/\?]*(?:\?.*)?)|(?:ht` +
			`tps?://(?:www\.)?audi-mediacenter\.com/(?:en|de)/audimediatv/(?:video/)?(?:[^/?#` +
			`]+))|(?:https?://(?:www\.)?audiomack\.com/song/(?:[\w/-]+))|(?:https?://[^/]+\.b` +
			`andcamp\.com/track/(?:[^/?#&]+))|(?:https?://(?:www\.)?bandcamp\.com/?\?(?:.*?&)` +
			`?show=(?:\d+))|(?:https?://(?:www\.)?beeg\.com/(?:\d+))|(?:https?://(?:www\.|pro` +
			`\.)?beatport\.com/track/(?:[^/]+)/(?:[0-9]+))|(?:https?://(?:www\.)?bigflix\.com` +
			`/.+/(?:[0-9]+))|(?:https?://(?:www\.)?bild\.de/(?:[^/]+/)+(?:[^/]+)-(?:\d+)(?:,a` +
			`uto=true)?\.bild\.html)|(?:https?://(?:www\.)?bitchute\.com/(?:video|embed|torre` +
			`nt/[^/]+)/(?:[^/?#&]+))|(?:https?://(?:www\.)?bleacherreport\.com/video_embed\?i` +
			`d=(?:[0-9a-f-]{36}))|(?:https?://(?:www\.)?bpb\.de/mediathek/(?:[0-9]+)/)|(?:(?:` +
			`https?://(?:www\.)?br(?:-klassik)?\.de)/(?:[a-z0-9\-_]+/)+(?:[a-z0-9\-_]+)\.html` +
			`)|(?:(?:https?://.*brightcove\.com/(services|viewer).*?\?|brightcove:)(?:.*))|(?` +
			`:https?://players\.brightcove\.net/(?:\d+)/(?:[^/]+)_(?:[^/]+)/index\.html\?.*vi` +
			`deoId=(?:\d+|ref:[^&]+))|(?:https?://(?:[^/]+\.)?businessinsider\.(?:com|nl)/(?:` +
			`[^/]+/)*(?:[^/?#&]+))|(?:https?://(?:www\.)?camdemy\.com/media/(?:\d+))|(?:https` +
			`?://(?:www\.)?(?:mycanal|piwiplus)\.fr/(?:[^/]+/)*(?:[^?/]+)(?:\.html\?.*\bvid=|` +
			`/p/)(?:\d+))|(?:https?://(?:(?:www\.)?canalc2\.tv/video/|archives-canalc2\.u-str` +
			`asbg\.fr/video\.asp\?.*\bidVideo=)(?:\d+))|(?:https?://(?:www\.)?media\.ccc\.de/` +
			`v/(?:[^/?#&]+))|(?:https?://(?:www\.)?charlierose\.com/(?:video|episode)(?:s|/pl` +
			`ayer)/(?:\d+))|(?:https?://(?:www\.)?chirb\.it/(?:(?:wp|pl)/|fb_chirbit_player\.` +
			`swf\?key=)?(?:[\da-zA-Z]+))|(?:https?://player\.cinchcast\.com/.*?(?:assetId|sho` +
			`w_id)=(?:[0-9]+))|(?:https?://(?:www\.)?clippituser\.tv/c/(?:[a-z]+))|(?:https?:` +
			`//(?:chic|www)\.clipsyndicate\.com/video/play(list/\d+)?/(?:\d+))|(?:https?://(?` +
			`:www\.)?clyp\.it/(?:[a-z0-9]+))|(?:https?://(?:(?:edition|www|money)\.)?cnn\.com` +
			`/(?:video/(?:data/.+?|\?)/)?videos?/(?:.+?/(?:[^/]+?)(?:\.(?:[a-z\-]+)|(?=&))))|` +
			`(?:https?://[^\.]+\.blogs\.cnn\.com/.+)|(?:https?://(?:(?:edition|www)\.)?cnn\.c` +
			`om/(?!videos?/))|(?:(?:coub:|https?://(?:coub\.com/(?:view|embed|coubs)/|c-cdn\.` +
			`coub\.com/fb-player\.swf\?.*\bcoub(?:ID|id)=))(?:[\da-z]+))|(?:https?://(?:www\.` +
			`)?cracked\.com/video_(?:\d+)_[\da-z-]+\.html)|(?:https?://(?:www\.)?c-span\.org/` +
			`video/\?(?:[0-9a-f]+))|(?:https?://news\.cts\.com\.tw/[a-z]+/[a-z]+/\d+/(?:\d+)\` +
			`.html)|(?:https?://(?:app\.)?curiositystream\.com/video/(?:\d+))|(?:https?://(?:` +
			`www\.)?dailymail\.co\.uk/(?:video/[^/]+/video-|embed/video/)(?:[0-9]+))|(?:(?i)h` +
			`ttps?://(?:(www|touch)\.)?dailymotion\.[a-z]{2,3}/(?:(?:(?:embed|swf|#)/)?video|` +
			`swf)/(?:[^/?_]+))|(?:https?://(?:www\.)?digg\.com/video/(?:[^/?#&]+))|(?:https?:` +
			`//(?:www\.)?dotsub\.com/view/(?:[^/]+))|(?:https?://(?:www\.)?(?:discovery|tlc|a` +
			`nimalplanet|dmax)\.de/(?:.*\#(?:\d+)|(?:[^/]+/)*videos/(?:[^/?#]+)|programme/(?:` +
			`[^/]+)/video/(?:[^/]+)))|(?:https?://(?:(?:[^/]+\.)?(?:disney\.[a-z]{2,3}(?:\.[a` +
			`-z]{2})?|disney(?:(?:me|latino)\.com|turkiye\.com\.tr|channel\.de)|(?:starwars|m` +
			`arvelkids)\.com))/(?:(?:embed/|(?:[^/]+/)+[\w-]+-)(?:[a-z0-9]{24})|(?:[^/]+/)?(?` +
			`:[^/?#]+)))|(?:https?://(?:s?evt\.dispeak|events\.digitallyspeaking)\.com/(?:[^/` +
			`]+/)+xml/(?:[^.]+)\.xml)|(?:https?://(?:www\.)?dw\.com/(?:[^/]+/)+(?:av|e)-(?:\d` +
			`+))|(?:https?://(?:www\.)?ebaumsworld\.com/videos/[^/]+/(?:\d+))|(?:https?://(?:` +
			`www\.)?echo\.msk\.ru/sounds/(?:\d+))|(?:https?://(?:[^.]+\.)?elpais\.com/.*/(?:[` +
			`^/#?]+)\.html(?:$|[?#]))|(?:https?://(?:www\.)?engadget\.com/video/(?:[^/?#]+))|` +
			`(?:https?://ec\.europa\.eu/avservices/(?:video/player|audio/audioDetails)\.cfm\?` +
			`.*?\bref=(?:[A-Za-z0-9-]+))|(?:https?://(?:www\.)?extremetube\.com/(?:[^/]+/)?vi` +
			`deo/(?:[^/#?&]+))|(?:(?:https?://(?:[\w-]+\.)?(?:facebook\.com|facebookcorewwwi\` +
			`.onion)/(?:[^#]*?\#!/)?(?:(?:video/video\.php|photo\.php|video\.php|video/embed|` +
			`story\.php)\?(?:.*?)(?:v|video_id|story_fbid)=|[^/]+/videos/(?:[^/]+/)?|[^/]+/po` +
			`sts/|groups/[^/]+/permalink/)|facebook:)(?:[0-9]+))|(?:https?://(?:[\w-]+\.)?fac` +
			`ebook\.com/plugins/video\.php\?.*?\bhref=(?:https.+))|(?:https?://(?:www\.)?faz\` +
			`.net/(?:[^/]+/)*.*?-(?:\d+)\.html)|(?:(?:5min:|https?://(?:[^/]*?5min\.com/|deli` +
			`very\.vidible\.tv/aol)(?:(?:Scripts/PlayerSeed\.js|playerseed/?)?\?.*?playList=)` +
			`?)(?:\d+))|(?:https?://(?:www\.|secure\.)?flickr\.com/photos/[\w\-_@]+/(?:\d+))|` +
			`(?:https?://(?:www\.)?formula1\.com/(?:content/fom-website/)?en/video/\d{4}/\d{1` +
			`,2}/(?:.+?)\.html)|(?:https?://(?:video\.(?:insider\.)?fox(?:news|business)\.com` +
			`)/v/(?:video-embed\.html\?video_id=)?(?:\d+))|(?:https?://(?:www\.)?(?:insider\.` +
			`)?foxnews\.com/(?!v)([^/]+/)+(?:[a-z-]+))|(?:https?://(?:www\.)?franceculture\.f` +
			`r/emissions/(?:[^/]+/)*(?:[^/?#&]+))|(?:https?://(?:www\.)?freesound\.org/people` +
			`/[^/]+/sounds/(?:[^/]+))|(?:https?://(?:www\.)?gamespot\.com/(?:video|article|re` +
			`view)s/(?:[^/]+/\d+-|embed/)(?:\d+))|(?:https?://(?:www\.)?gaskrank\.tv/tv/(?:[^` +
			`/]+)/(?:[^/]+)\.htm)|(?:https?://(?:www\.)?gdcvault\.com/play/(?:\d+)/(?:(\w|-)+` +
			`)?)|(?:https?://(?:www\.)?gfycat\.com/(?:ifr/|gifs/detail/)?(?:[^/?#]+))|(?:http` +
			`s?://(?:www\.)?godtube\.com/watch/\?v=(?:[\da-zA-Z]+))|(?:^https?://video\.golem` +
			`\.de/.+?/(?:.+?)/)|(?:https?://on-demand\.gputechconf\.com/gtc/2015/video/S(?:\d` +
			`+)\.html)|(?:https?://(?:www\.)?historicfilms\.com/(?:tapes/|play)(?:\d+))|(?:ht` +
			`tps?://(?:www\.)?hitrecord\.org/records/(?:\d+))|(?:http?://(?:www\.)?hornbunny\` +
			`.com/videos/(?:[a-z-]+)-(?:\d+)\.html)|(?:https?://[\da-z-]+\.(?:howstuffworks|s` +
			`tuff(?:(?:youshould|theydontwantyouto)know|toblowyourmind|momnevertoldyou)|(?:br` +
			`ain|car)stuffshow|fwthinking|geniusstuff)\.com/(?:[^/]+/)*(?:\d+-)?(?:.+?)-video` +
			`\.htm)|(?:https?://.+?\.ign\.com/(?:[^/]+/)?(?:videos|show_videos|articles|featu` +
			`re|(?:[^/]+/\d+/video))(/.+)?/(?:.+))|(?:https?://(?:www|m)\.imdb\.com/(?:video|` +
			`title|list).+?[/-]vi(?:\d+))|(?:https?://(?:i\.)?imgur\.com/(?!(?:a|gallery|(?:t` +
			`(?:opic)?|r)/[^/]+)/)(?:[a-zA-Z0-9]+))|(?:https?://(?:i\.)?imgur\.com/(?:gallery` +
			`|(?:t(?:opic)?|r)/[^/]+)/(?:[a-zA-Z0-9]+))|(?:https?://(?:www\.)?ina\.fr/video/(` +
			`?:I?[A-Z0-9]+))|(?:https?://(?:www\.)?infoq\.com/(?:[^/]+/)+(?:[^/]+))|(?:(?:htt` +
			`ps?://(?:www\.)?instagram\.com/p/(?:[^/?#&]+)))|(?:https?://(?:www\.)?90tv\.ir/v` +
			`ideo/(?:[0-9]+)/.*)|(?:https?://(?:www\.)?ivideon\.com/tv/(?:[^/]+/)*camera/(?:\` +
			`d+-[\da-f]+)/(?:\d+))|(?:https?://(?:(?:www|m)\.)?izlesene\.com/(?:video|embedpl` +
			`ayer)/(?:[^/]+/)?(?:[0-9]+))|(?:https?://(?:licensing\.jamendo\.com/[^/]+|(?:www` +
			`\.)?jamendo\.com)/track/(?:[0-9]+)/(?:[^/?#&]+))|(?:https?://.*?\.jeuxvideo\.com` +
			`/.*/(.*?)\.htm)|(?:(?:joj:|https?://media\.joj\.sk/embed/)(?:[^/?#^]+))|(?:(?:ht` +
			`tps?://(?:content\.jwplatform|cdn\.jwplayer)\.com/(?:(?:feed|player|thumb|previe` +
			`w|video|manifest)s|jw6|v2/media)/|jwplatform:)(?:[a-zA-Z0-9]{8}))|(?:https?://(?` +
			`:www\.)?keezmovies\.com/video/(?:(?:[^/]+)-)?(?:\d+))|(?:https?://(?:www\.)?kick` +
			`starter\.com/projects/(?:[^/]*)/.*)|(?:https?://krasview\.ru/(?:video|embed)/(?:` +
			`\d+))|(?:https?://(?:www\.)?lci\.fr/[^/]+/[\w-]+-(?:\d+)\.html)|(?:https?://(?:w` +
			`ww\.)?loc\.gov/(?:item/|today/cyberlc/feature_wdesc\.php\?.*\brec=)(?:[0-9a-z_.]` +
			`+))|(?:(?:limelight:media:|https?://(?:link\.videoplatform\.limelight\.com/media` +
			`/|assets\.delvenetworks\.com/player/loader\.swf)\?.*?\bmediaId=)(?:[a-z0-9]{32})` +
			`)|(?:https?://(?:new\.)?livestream\.com/(?:accounts/(?:\d+)|(?:[^/]+))/(?:events` +
			`/(?:\d+)|(?:[^/]+))(?:/videos/(?:\d+))?)|(?:https?://(?:www\.)?lovehomeporn\.com` +
			`/video/(?:\d+)(?:/(?:[^/?#&]+))?)|(?:https?://(?:www\.)?macgamestore\.com/mediav` +
			`iewer\.php\?trailer=(?:\d+))|(?:(?i)https?://(?:www\.)?manyvids\.com/video/(?:\d` +
			`+))|(?:https?://(?:www\.)?massengeschmack\.tv/play/(?:[^?&#]+))|(?:https://playe` +
			`r\.megaphone\.fm/(?:[A-Z0-9]+))|(?:https?://(?:www\.)?metacritic\.com/.+?/traile` +
			`rs/(?:\d+))|(?:(?:mva:|https?://(?:mva\.microsoft|(?:www\.)?microsoftvirtualacad` +
			`emy)\.com/[^/]+/training-courses/[^/?#&]+-)(?:\d+)(?::|\?l=)(?:[\da-zA-Z]+_\d+))` +
			`|(?:https?://(?:[\da-z_-]+\.)*(?:mlb)\.com/(?:(?:(?:[^/]+/)*c-|(?:shared/video/e` +
			`mbed/(?:embed|m-internal-embed)\.html|(?:[^/]+/)+(?:play|index)\.jsp|)\?.*?\bcon` +
			`tent_id=)(?:\d+)))|(?:https?://(?:www\.)?mofosex\.com/videos/(?:\d+)/(?:[^/?#&.]` +
			`+)\.html)|(?:https?://(?:www\.)?mojvideo\.com/video-(?:[^/]+)/(?:[a-f0-9]+))|(?:` +
			`https?://myspace\.com/[^/]+/(?:video/[^/]+/(?:\d+)|music/song/[^/?#&]+-(?:\d+)-\` +
			`d+(?:[/?#&]|$)))|(?:(?:https?://(?:www\.)?myvi\.(?:(?:ru/player|tv)/(?:(?:embed/` +
			`html|flash|api/Video/Get)/|content/preloader\.swf\?.*\bid=)|ru/watch/)|myvi:)(?:` +
			`[\da-zA-Z_-]+))|(?:https?://(?:watch\.|www\.)?nba\.com/(?:(?:[^/]+/)+(?:[^?]*?))` +
			`/?(?:/index\.html)?(?:\?.*)?$)|(?:https?://(?:www\.)?ndr\.de/(?:[^/]+/)*(?:[^/?#` +
			`]+),[\da-z]+\.html)|(?:https?://(?:www\.)?ndr\.de/(?:[^/]+/)*(?:[\da-z]+)-(?:pla` +
			`yer|externalPlayer)\.html)|(?:https?://(?:www\.)?n-joy\.de/(?:[^/]+/)*(?:[\da-z]` +
			`+)-(?:player|externalPlayer)_[^/]+\.html)|(?:https?://(?:[^/]+\.)?ndtv\.com/(?:[` +
			`^/]+/)*videos?/?(?:[^/]+/)*[^/?^&]+-(?:\d+))|(?:https?://(?:www\.)?netzkino\.de/` +
			`\#!/(?:[^/]+)/(?:[^/]+))|(?:https?://(?:www\.)?newgrounds\.com/(?:audio/listen|p` +
			`ortal/view)/(?:[0-9]+))|(?:https?://(?:www\.)?nexttv\.com\.tw/(?:[^/]+/)+(?:\d+)` +
			`)|(?:(?:https?://api\.nexx(?:\.cloud|cdn\.com)/v3/(?:\d+)/videos/byid/|nexx:(?:(` +
			`?:\d+):)?|https?://arc\.nexx\.cloud/api/video/)(?:\d+))|(?:https?://(?:www\.)?(?` +
			`:nhl|wch2016)\.com/(?:[^/]+/)*c-(?:\d+))|(?:https?://media\.cms\.nova\.cz/embed/` +
			`(?:[^/?#&]+))|(?:https?://(?:(?:www|cn)\.)?nowness\.com/(?:story|(?:series|categ` +
			`ory)/[^/]+)/(?:[^/]+?)(?:$|[?#]))|(?:https?://(?:www\.)?ntv\.ru/(?:[^/]+/)*(?:[^` +
			`/?#&]+))|(?:https?://(?:(?:www|m|mobile)\.)?(?:odnoklassniki|ok)\.ru/(?:video(?:` +
			`embed)?/|web-api/video/moviePlayer/|live/|dk\?.*?st\.mvId=)(?:[\d-]+))|(?:(?:ooy` +
			`ala:|https?://.+?\.ooyala\.com/.*?(?:embedCode|ec)=)(?:.+?)(&|$))|(?:https?://(?` +
			`:www\.)?outsidetv\.com/(?:[^/]+/)*?play/[a-zA-Z0-9]{8}/\d+/\d+/(?:[a-zA-Z0-9]{8}` +
			`))|(?:https?://(?:(?:www\.)?packtpub\.com/mapt|subscription\.packtpub\.com)/vide` +
			`o/[^/]+/(?:\d+)/(?:\d+)/(?:\d+))|(?:https?://(?:(?:www\.)?pandora\.tv/view/(?:[^` +
			`/]+)/(?:\d+)|(?:.+?\.)?channel\.pandora\.tv/channel/video\.ptv\?|m\.pandora\.tv/` +
			`?\?))|(?:https?://(?:www\.)?patreon\.com/(?:creation\?hid=|posts/(?:[\w-]+-)?)(?` +
			`:\d+))|(?:https?://(?:www\.)?pearvideo\.com/video_(?:\d+))|(?:https?://(?:www\.)` +
			`?people\.com/people/videos/0,,(?:\d+),00\.html)|(?:https?://(?:[a-z0-9]+\.)?phot` +
			`obucket\.com/.*(([\?\&]current=)|_)(?:.*)\.(?:(flv)|(mp4)))|(?:https?://(?:www\.` +
			`)?play\.fm/(?:(?:[^/]+/)+(?:[^/]+))/?(?:$|[?#]))|(?:https?://(?:www\.)?plays\.tv` +
			`/(?:video|embeds)/(?:[0-9a-f]{18}))|(?:https?://(?:www\.)?playvid\.com/watch(\?v` +
			`=|/)(?:.+?)(?:#|$))|(?:(?:https?)://(?:(?:[^.]+)\.podomatic\.com/entry|(?:www\.)` +
			`?podomatic\.com/podcasts/(?:[^/]+)/episodes)/(?:[^/?#&]+))|(?:https?://(?:www\.)` +
			`?pokemon\.com/[a-z]{2}(?:.*?play=(?:[a-z0-9]{32})|/(?:[^/]+/)+(?:[^/?#&]+)))|(?:` +
			`(?:https?://)(?:www\.|)91porn\.com/.+?\?viewkey=(?:[\w\d]+))|(?:https?://(?:[a-z` +
			`A-Z]+\.)?porn\.com/videos/(?:(?:[^/]+)-)?(?:\d+))|(?:https?://(?:www\.)?pornhd\.` +
			`com/(?:[a-z]{2,4}/)?videos/(?:\d+)(?:/(?:.+))?)|(?:https?://(?:(?:[^/]+\.)?(?:po` +
			`rnhub\.(?:com|net))/(?:(?:view_video\.php|video/show)\?viewkey=|embed/)|(?:www\.` +
			`)?thumbzilla\.com/video/)(?:[\da-z]+))|(?:https?://(?:\w+\.)?pornotube\.com/(?:[` +
			`^?#]*?)/video/(?:[0-9]+))|(?:https?://(?:www\.)?puhutv\.com/(?:[^/?#&]+)-izle)|(` +
			`?:https?://(?:www\.)?presstv\.ir/[^/]+/(?:\d+)/(?:\d+)/(?:\d+)/(?:\d+)/(?:[^/]+)` +
			`?)|(?:https?://(?:.+?)\.(?:radio\.(?:de|at|fr|pt|es|pl|it)|rad\.io))|(?:https?:/` +
			`/(?:www\.)?radiojavan\.com/videos/video/(?:[^/]+)/?)|(?:https?://[^/]+\.(?:rai\.` +
			`(?:it|tv)|rainews\.it)/.+?-(?:[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f` +
			`]{12})(?:-.+?)?\.html)|(?:https?://(?:videos\.raywenderlich\.com/courses|(?:www\` +
			`.)?raywenderlich\.com)/(?:[^/]+)/lessons/(?:\d+))|(?:https?://(?:www\.)?(?:rbmar` +
			`adio|redbullradio)\.com/shows/(?:[^/]+)/episodes/(?:[^/?#&]+))|(?:https?://(?:(?` +
			`:www\.)?redtube\.com/|embed\.redtube\.com/\?.*?\bid=)(?:[0-9]+))|(?:(?:rentv:|ht` +
			`tps?://(?:www\.)?ren\.tv/(?:player|video/epizod)/)(?:\d+))|(?:^https?://(?:www\.` +
			`)?reverbnation\.com/.*?/song/(?:\d+).*?$)|(?:https?://(?:www\.)?rockstargames\.c` +
			`om/videos(?:/video/|#?/?\?.*\bvideo=)(?:\d+))|(?:https?://(?:www\.)?prehravac\.r` +
			`ozhlas\.cz/audio/(?:[0-9]+))|(?:rts:(?:\d+)|https?://(?:.+?\.)?rts\.ch/(?:[^/]+/` +
			`){2,}(?:[0-9]+)-(?:.+?)\.html)|(?:https?://(?:www\.)?rtvs\.sk/(?:radio|televizia` +
			`)/archiv/\d+/(?:\d+))|(?:https?://(?:test)?player\.(?:rutv\.ru|vgtrk\.com)/(?:fl` +
			`ash\d+v/container\.swf\?id=|iframe/(?:swf|video|live)/id/|index/iframe/cast_id/)` +
			`(?:\d+))|(?:https?://(?:(?:v2|www)\.)?videos\.sapo\.(?:pt|cv|ao|mz|tl)/(?:[\da-z` +
			`A-Z]{20}))|(?:https?://(?:www\.)?screencast\.com/t/(?:[a-zA-Z0-9]+))|(?:https?:/` +
			`/(?:www\.)?senate\.gov/isvp/?\?(?:.+))|(?:https?://(?:www\.)?seznamzpravy\.cz/if` +
			`rame/player\?.*\bsrc=)|(?:https?://(?:www\.)?skysports\.com/watch/video/(?:[0-9]` +
			`+))|(?:https?://(?:www\.)?slideshare\.net/[^/]+?/(?:.+?)($|\?))|(?:https?://(?:\` +
			`w+\.)?slutload\.com/(?:video/[^/]+|embed_player|watch)/(?:[^/]+))|(?:https?://(?` +
			`:www\.)?soundgasm\.net/u/(?:[0-9a-zA-Z_-]+)/(?:[0-9a-zA-Z_-]+))|(?:https?://(?:w` +
			`ww\.)?stitcher\.com/podcast/(?:[^/]+/)+e/(?:(?:[^/#?&]+?)-)?(?:\d+)(?:[/#?&]|$))` +
			`|(?:https?://(?:(?:www|play)\.)?(?:srf|rts|rsi|rtr|swissinfo)\.ch/play/(?:tv|rad` +
			`io)/[^/]+/(?:video|audio)/[^?]+\?id=(?:[0-9a-f\-]{36}|\d+))|(?:https?://openclas` +
			`sroom\.stanford\.edu(?:/?|(/MainFolder/(?:HomePage|CoursePage|VideoPage)\.php([?` +
			`]course=(?:[^&]+)(&video=(?:[^&]+))?(&.*)?)?))$)|(?:https?://streamable\.com/(?:` +
			`[es]/)?(?:\w+))|(?:https?://(?:(?:www\.)?sunporno\.com/videos|embeds\.sunporno\.` +
			`com/embed)/(?:\d+))|(?:https?://(?:www\.)?swrmediathek\.de/(?:content/)?player\.` +
			`htm\?show=(?:[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}))|(?:https?` +
			`://(?:www\.)?tagesschau\.de/(?:[^/]+/(?:[^/]+/)*?(?:[^/#?]+?(?:-?[0-9]+)?))(?:~_` +
			`?[^/#?]+?)?\.html)|(?:https?://(?:www\.)?tastytrade\.com/tt/shows/[^/]+/episodes` +
			`/(?:[^/?#&]+))|(?:https?://tds\.lifeway\.com/v1/trainingdeliverysystem/courses/(` +
			`?:\d+)/index\.html)|(?:https?://(?:www\.)?teachertube\.com/(viewVideo\.php\?vide` +
			`o_id=|music\.php\?music_id=|video/(?:[\da-z-]+-)?|audio/)(?:\d+))|(?:(?:https?:/` +
			`/)(?:www|embed(?:-ssl)?)(?:\.ted\.com/((?:playlists(?:/\d+)?)|((?:talks))|(?:wat` +
			`ch)/[^/]+/[^/]+)(/lang/(.*?))?/(?:[\w-]+).*)$)|(?:^https?://(?:www\.)?t13\.cl/vi` +
			`deos(?:/[^/]+)+/(?:[\w-]+))|(?:https?://(?:www\.)?tenta\.com/how-to-download-vid` +
			`eos)|(?:https?://(?:www\.)?thisoldhouse\.com/(?:watch|how-to|tv-episode)/(?:[^/?` +
			`#]+))|(?:https?://(?:m\.)?tiktok\.com/v/(?:\d+))|(?:https?://(?:.+?\.)?tinypic\.` +
			`com/player\.php\?v=(?:[^&]+)&s=\d+)|(?:https?://player\.(?:tna|emp)flix\.com/vid` +
			`eo/(?:\d+))|(?:https?://(?:www\.)?tnaflix\.com/[^/]+/(?:[^/]+)/video(?:\d+))|(?:` +
			`https?://(?:www\.)?empflix\.com/(?:videos/(?:.+?)-|[^/]+/(?:[^/]+)/video)(?:[0-9` +
			`]+))|(?:https?://(?:www\.)?moviefap\.com/videos/(?:[0-9a-f]+)/(?:[^/]+)\.html)|(` +
			`?:https?://videos\.toypics\.net/view/(?:[0-9]+))|(?:https?://(?:(?:www|m)\.)?tri` +
			`lulilu\.ro/(?:[^/]+/)?(?:[^/#\?]+))|(?:https?://(?:www\.)?tube8\.com/(?:[^/]+/)+` +
			`(?:[^/]+)/(?:\d+))|(?:https?://(?:[^/?#&]+)\.tumblr\.com/(?:post|video)/(?:[0-9]` +
			`+)(?:$|[/?#]))|(?:https?://(?:(?:www\.)?tune\.pk/(?:video/|player/embed_player.p` +
			`hp?.*?\bvid=)|embed\.tune\.pk/play/)(?:\d+))|(?:https?://(?:www\.)?tvanouvelles\` +
			`.ca/videos/(?:\d+))|(?:https?://(?:www\.)?tvc\.ru/video/iframe/id/(?:\d+))|(?:ht` +
			`tps?://(?:www\.)?tvc\.ru/(?!video/iframe/id/)(?:[^?#]+))|(?:https?://(?:(?:[^/]+` +
			`)\.)?tvn24(?:bis)?\.pl/(?:[^/]+/)*(?:[^/]+))|(?:(?:tvp:|https?://[^/]+\.tvp\.(?:` +
			`pl|info)/sess/tvplayer\.php\?.*?object_id=)(?:\d+))|(?:https?://[^/]+\.tvp\.(?:p` +
			`l|info)/(?:video/(?:[^,\s]*,)*|(?:(?!\d+/)[^/]+/)*)(?:\d+))|(?:https?://tvplay\.` +
			`(?:tv3\.lt|skaties\.lv|tv3\.ee)/[^/]+/[^/?#&]+-(?:\d+))|(?:https?://(?:www\.)?20` +
			`min\.ch/(?:videotv/*\?.*?\bvid=|videoplayer/videoplayer\.html\?.*?\bvideoId@)(?:` +
			`\d+))|(?:https?://(?:clips\.twitch\.tv/(?:[^/]+/)*|(?:www\.)?twitch\.tv/[^/]+/cl` +
			`ip/)(?:[^/?#&]+))|(?:https?://amp\.twimg\.com/v/(?:[0-9a-f\-]{36}))|(?:https?://` +
			`video\.udn\.com/(?:embed|play)/news/(?:\d+))|(?:https?://(?:www\.)?(?:digiteka\.` +
			`net|ultimedia\.com)/(?:deliver/(?:generic|musique)(?:/[^/]+)*/(?:src|article)|de` +
			`fault/index/video(?:generic|music)/id)/(?:[\d+a-z]+))|(?:https?://utv\.unistra\.` +
			`fr/(?:index|video)\.php\?id_video\=(?:\d+))|(?:https?://(?:.+?\.)?uol\.com\.br/.` +
			`*?(?:(?:mediaId|v)=|view/(?:[a-z0-9]+/)?|video(?:=|/(?:\d{4}/\d{2}/\d{2}/)?))(?:` +
			`\d+|[\w-]+-[A-Z0-9]+))|(?:https?://(?:www\.)?usatoday\.com/(?:[^/]+/)*(?:[^?/#]+` +
			`))|(?:https?://(?:(?:app|embed)\.)?ustudio\.com/embed/(?:[^/]+)/(?:[^/]+))|(?:ht` +
			`tps?://(?:www\.)?video\.varzesh3\.com/(?:[^/]+/)+(?:[^/]+)/?)|(?:https?://(?:[^/` +
			`]+\.)?vbox7\.com/(?:play:|(?:emb/external\.php|player/ext\.swf)\?.*?\bvid=)(?:[\` +
			`da-fA-F]+))|(?:https?://veehd\.com/video/(?:\d+))|(?:https?://(?:.+?\.)?vesti\.r` +
			`u/(?:.+))|(?:(?:https?://(?:www\.)?vevo\.com/watch/(?!playlist|genre)(?:[^/]+/(?` +
			`:[^/]+/)?)?|https?://cache\.vevo\.com/m/html/embed\.html\?video=|https?://videop` +
			`layer\.vevo\.com/embed/embedded\?videoId=|vevo:)(?:[^&?#]+))|(?:(?:https?://(?:w` +
			`ww\.)?(?:vgtv.no|bt.no/tv|aftenbladet.no/tv|fvn.no/fvntv|aftenposten.no/webtv|ap` +
			`.vgtv.no/webtv|tv.aftonbladet.se/abtv|www.aftonbladet.se/tv)/?(?:(?:\#!/)?(?:vid` +
			`eo|live)/|embed?.*id=|a(?:rticles)?/)|(?:vgtv|bttv|satv|fvntv|aptv|abtv):)(?:\d+` +
			`))|(?:https?://(?:www\.)?viddler\.com/(?:v|embed|player)/(?:[a-z0-9]+))|(?:https` +
			`?://videopress\.com/embed/(?:[\da-zA-Z]+))|(?:https?://(?:www\.|m\.|)videosz\.co` +
			`m/[a-z]+/[a-z]+/(?:[0-9]+)_)|(?:https?://(?:www\.)?vidlii\.com/(?:watch|embed)\?` +
			`.*?\bv=(?:[0-9A-Za-z_-]{11}))|(?:https?://(?:(?:www|(?:player))\.)?vimeo(?:pro)?` +
			`\.com/(?!(?:channels|album)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)(?:.*?/)` +
			`?(?:(?:play_redirect_hls|moogaloop\.swf)\?clip_id=)?(?:videos?/)?(?:[0-9]+)(?:/[` +
			`\da-f]+)?/?(?:[?&].*)?(?:[#].*)?$)|(?:https?://(?:www\.)?vimeo\.com/ondemand/(?:` +
			`[^/?#&]+))|(?:https?://(?:player\.vimple\.(?:ru|co)/iframe|vimple\.(?:ru|co))/(?` +
			`:[\da-f-]{32,36}))|(?:https?://(?:www\.)?vine\.co/(?:v|oembed)/(?:\w+))|(?:(?:vi` +
			`qeo:|https?://cdn\.viqeo\.tv/embed/*\?.*?\bvid=|https?://api\.viqeo\.tv/v\d+/dat` +
			`a/startup?.*?\bvideo(?:%5B%5D|\[\])=)(?:[\da-f]+))|(?:https?://(?:(?:(?:(?:m|new` +
			`)\.)?vk\.com/video_|(?:www\.)?daxab.com/)ext\.php\?(?:.*?\boid=(?:-?\d+).*?\bid=` +
			`(?:\d+).*)|(?:(?:(?:m|new)\.)?vk\.com/(?:.+?\?.*?z=)?video|(?:www\.)?daxab.com/e` +
			`mbed/)(?:-?\d+_\d+)(?:.*\blist=(?:[\da-f]+))?))|(?:https?://(?:(?:www|m)\.)?vliv` +
			`e\.tv/video/(?:[0-9]+))|(?:https?://(?:m\.)?vuclip\.com/w\?.*?cid=(?:[0-9]+))|(?` +
			`:https?://(?:(?:www|view)\.)?vzaar\.com/(?:videos/)?(?:\d+))|(?:(?:washingtonpos` +
			`t:|https?://(?:www\.)?washingtonpost\.com/video/(?:[^/]+/)*)(?:[\da-f]{8}-[\da-f` +
			`]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}))|(?:(?:wat:|https?://(?:www\.)?wat\.tv/v` +
			`ideo/.*-)(?:[0-9a-z]+))|(?:https?://m\.weibo\.cn/status/(?:[0-9]+)(\?.+)?)|(?:ht` +
			`tps?://(?:www|m)\.worldstar(?:candy|hiphop)\.com/(?:videos|android)/video\.php\?` +
			`.*?\bv=(?:[^&]+))|(?:https?://(?:.+?\.)?xhamster\.com/(?:movies/(?:\d+)/(?:[^/]*` +
			`)\.html|videos/(?:[^/]*)-(?:\d+)))|(?:https?://(?:.+?\.)?xhamster\.com/xembed\.p` +
			`hp\?video=(?:\d+))|(?:https?://(?:video|www)\.xnxx\.com/video-?(?:[0-9a-z]+)/)|(` +
			`?:(?:xtube:|https?://(?:www\.)?xtube\.com/(?:watch\.php\?.*\bv=|video-watch/(?:e` +
			`mbedded/)?(?:[^/]+)-))(?:[^/?&#]+))|(?:https?://(?:(?:www\.)?xvideos\.com/video|` +
			`flashservice\.xvideos\.com/embedframe/|static-hw\.xvideos\.com/swf/xv-player\.sw` +
			`f\?.*?\bid_video=)(?:[0-9]+))|(?:https?://(?:www\.)?xxxymovies\.com/videos/(?:\d` +
			`+)/(?:[^/]+))|(?:https?://v\.yinyuetai\.com/video(?:/h5)?/(?:[0-9]+))|(?:https?:` +
			`//(?:\w+\.)?youjizz\.com/videos/(?:[^/#?]*-(?:\d+)\.html|embed/(?:\d+)))|(?:http` +
			`s?://(?:www\.)?youporn\.com/watch/(?:\d+)/(?:[^/?#&]+))|(?:https?://(?:www\.)?yo` +
			`urporn\.sexy/post/(?:[^/?#&.]+))|(?:https?://(?:www\.)?(?:yourupload\.com/(?:wat` +
			`ch|embed)|embed\.yourupload\.com)/(?:[A-Za-z0-9]+))|(?:^((?:https?://|//)(?:(?:(` +
			`?:(?:\w+\.)?[yY][oO][uU][tT][uU][bB][eE](?:-nocookie)?\.com/|(?:www\.)?deturl\.c` +
			`om/www\.youtube\.com/|(?:www\.)?pwnyoutube\.com/|(?:www\.)?hooktube\.com/|(?:www` +
			`\.)?yourepeat\.com/|tube\.majestyc\.net/|(?:www\.)?invidio\.us/|youtube\.googlea` +
			`pis\.com/)(?:.*?\#/)?(?:(?:(?:v|embed|e)/(?!videoseries))|(?:(?:(?:watch|movie)(` +
			`?:_popup)?(?:\.php)?/?)?(?:\?|\#!?)(?:.*?[&;])??v=)))|(?:youtu\.be|vid\.plus|zwe` +
			`arz\.com/watch|)/|(?:www\.)?cleanvideosearch\.com/media/action/yt/watch\?videoId` +
			`=))?([0-9A-Za-z_-]{11})(?!.*?\blist=(?:(?:PL|LL|EC|UU|FL|RD|UL|TL)[0-9A-Za-z-_]{` +
			`10,}|WL))$)`,
	}
}
