/**
 * Go Video Downloader
 *
 *    Copyright 2018 Tenta, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * For any questions, please contact developer@tenta.io
 *
 * masterregexp.go: Automatically generated regexp by combining URL validation expressions of all extractors
 */

// Code generated by transpiler. DO NOT EDIT.

package downloader

func init() {
	masterRegexps = []string{
		`(?:https?://abcnews\.go\.com/(?:[^/]+/video/(?:[0-9a-z-]+)-|video/embed\?.*?\bid` +
			`=)(?:\d+))|(?:https?://(?:(?:(?:embed|www)\.)?acast\.com/|play\.acast\.com/s/)(?` +
			`:[^/]+)/(?:[^/#?]+))|(?:https?://tv\.adobe\.com/(?:(?:fr|de|es|jp)/)?watch/(?:[^` +
			`/]+)/(?:[^/]+))|(?:https?://video\.tv\.adobe\.com/v/(?:\d+))|(?:(?:aol-video:|ht` +
			`tps?://(?:(?:www|on)\.)?aol\.com/(?:[^/]+/)*(?:[^/?#&]+-)?)(?:[^/?#&]+))|(?:http` +
			`s?://(?:www\.)?allocine\.fr/(?:article|video|film)/(?:fichearticle_gen_carticle=` +
			`|player_gen_cmedia=|fichefilm_gen_cfilm=|video-)(?:[0-9]+)(?:\.html)?)|(?:https?` +
			`://(?:www\.)?aparat\.com/(?:v/|video/video/embed/videohash/)(?:[a-zA-Z0-9]+))|(?` +
			`:(?:https?://(www\.)?daserste\.de/[^?#]+/videos/(?:[^/?#]+)-(?:[0-9]+))\.html)|(` +
			`?:^https?://(?:(?:(?:www|classic)\.)?ardmediathek\.de|mediathek\.(?:daserste|rbb` +
			`-online)\.de|one\.ard\.de)/(?:.*/)(?:[0-9]+|[^0-9][^/\?]+)[^/\?]*(?:\?.*)?)|(?:h` +
			`ttps?://(?:www\.)?audi-mediacenter\.com/(?:en|de)/audimediatv/(?:video/)?(?:[^/?` +
			`#]+))|(?:https?://(?:www\.)?audioboom\.com/(?:boos|posts)/(?:[0-9]+))|(?:https?:` +
			`//(?:www\.)?audiomack\.com/song/(?:[\w/-]+))|(?:https?://[^/]+\.bandcamp\.com/tr` +
			`ack/(?:[^/?#&]+))|(?:https?://(?:www\.)?bandcamp\.com/?\?(?:.*?&)?show=(?:\d+))|` +
			`(?:https?://(?:www\.)?beeg\.com/(?:\d+))|(?:https?://(?:www\.|pro\.)?beatport\.c` +
			`om/track/(?:[^/]+)/(?:[0-9]+))|(?:https?://(?:www\.)?bigflix\.com/.+/(?:[0-9]+))` +
			`|(?:https?://(?:www\.)?bild\.de/(?:[^/]+/)+(?:[^/]+)-(?:\d+)(?:,auto=true)?\.bil` +
			`d\.html)|(?:https?://(?:www\.)?bitchute\.com/(?:video|embed|torrent/[^/]+)/(?:[^` +
			`/?#&]+))|(?:https?://(?:www\.)?bleacherreport\.com/video_embed\?id=(?:[0-9a-f-]{` +
			`36}))|(?:https?://(?:www\.)?bpb\.de/mediathek/(?:[0-9]+)/)|(?:(?:https?://(?:www` +
			`\.)?br(?:-klassik)?\.de)/(?:[a-z0-9\-_]+/)+(?:[a-z0-9\-_]+)\.html)|(?:(?:https?:` +
			`//.*brightcove\.com/(services|viewer).*?\?|brightcove:)(?:.*))|(?:https?://playe` +
			`rs\.brightcove\.net/(?:\d+)/(?:[^/]+)_(?:[^/]+)/index\.html\?.*videoId=(?:\d+|re` +
			`f:[^&]+))|(?:https?://(?:[^/]+\.)?businessinsider\.(?:com|nl)/(?:[^/]+/)*(?:[^/?` +
			`#&]+))|(?:https?://(?:www\.)?camdemy\.com/media/(?:\d+))|(?:https?://(?:www\.)?(` +
			`?:mycanal|piwiplus)\.fr/(?:[^/]+/)*(?:[^?/]+)(?:\.html\?.*\bvid=|/p/)(?:\d+))|(?` +
			`:https?://(?:(?:www\.)?canalc2\.tv/video/|archives-canalc2\.u-strasbg\.fr/video\` +
			`.asp\?.*\bidVideo=)(?:\d+))|(?:https?://(?:www\.)?media\.ccc\.de/v/(?:[^/?#&]+))` +
			`|(?:https?://(?:www\.)?charlierose\.com/(?:video|episode)(?:s|/player)/(?:\d+))|` +
			`(?:https?://(?:www\.)?chirb\.it/(?:(?:wp|pl)/|fb_chirbit_player\.swf\?key=)?(?:[` +
			`\da-zA-Z]+))|(?:https?://player\.cinchcast\.com/.*?(?:assetId|show_id)=(?:[0-9]+` +
			`))|(?:https?://(?:www\.)?clippituser\.tv/c/(?:[a-z]+))|(?:https?://(?:chic|www)\` +
			`.clipsyndicate\.com/video/play(list/\d+)?/(?:\d+))|(?:https?://(?:www\.)?clyp\.i` +
			`t/(?:[a-z0-9]+))|(?:https?://(?:(?:edition|www|money)\.)?cnn\.com/(?:video/(?:da` +
			`ta/.+?|\?)/)?videos?/(?:.+?/(?:[^/]+?)(?:\.(?:[a-z\-]+)|(?=&))))|(?:https?://[^\` +
			`.]+\.blogs\.cnn\.com/.+)|(?:https?://(?:(?:edition|www)\.)?cnn\.com/(?!videos?/)` +
			`)|(?:(?:coub:|https?://(?:coub\.com/(?:view|embed|coubs)/|c-cdn\.coub\.com/fb-pl` +
			`ayer\.swf\?.*\bcoub(?:ID|id)=))(?:[\da-z]+))|(?:https?://(?:www\.)?cracked\.com/` +
			`video_(?:\d+)_[\da-z-]+\.html)|(?:https?://(?:www\.)?c-span\.org/video/\?(?:[0-9` +
			`a-f]+))|(?:https?://news\.cts\.com\.tw/[a-z]+/[a-z]+/\d+/(?:\d+)\.html)|(?:https` +
			`?://app\.curiositystream\.com/video/(?:\d+))|(?:https?://(?:www\.)?dailymail\.co` +
			`\.uk/(?:video/[^/]+/video-|embed/video/)(?:[0-9]+))|(?:(?i)https?://(?:(www|touc` +
			`h)\.)?dailymotion\.[a-z]{2,3}/(?:(?:(?:embed|swf|#)/)?video|swf)/(?:[^/?_]+))|(?` +
			`:https?://(?:www\.)?digg\.com/video/(?:[^/?#&]+))|(?:https?://(?:www\.)?dotsub\.` +
			`com/view/(?:[^/]+))|(?:https?://(?:www\.)?dr\.dk/(?:tv/se|nyheder|radio/ondemand` +
			`)/(?:[^/]+/)*(?:[\da-z-]+)(?:[/#?]|$))|(?:https?://(?:www\.)?(?:discovery|tlc|an` +
			`imalplanet|dmax)\.de/(?:.*\#(?:\d+)|(?:[^/]+/)*videos/(?:[^/?#]+)|programme/(?:[` +
			`^/]+)/video/(?:[^/]+)))|(?:https?://(?:(?:[^/]+\.)?(?:disney\.[a-z]{2,3}(?:\.[a-` +
			`z]{2})?|disney(?:(?:me|latino)\.com|turkiye\.com\.tr|channel\.de)|(?:starwars|ma` +
			`rvelkids)\.com))/(?:(?:embed/|(?:[^/]+/)+[\w-]+-)(?:[a-z0-9]{24})|(?:[^/]+/)?(?:` +
			`[^/?#]+)))|(?:https?://(?:s?evt\.dispeak|events\.digitallyspeaking)\.com/(?:[^/]` +
			`+/)+xml/(?:[^.]+)\.xml)|(?:https?://(?:www\.)?dw\.com/(?:[^/]+/)+(?:av|e)-(?:\d+` +
			`))|(?:https?://(?:www\.)?ebaumsworld\.com/videos/[^/]+/(?:\d+))|(?:https?://(?:w` +
			`ww\.)?echo\.msk\.ru/sounds/(?:\d+))|(?:https?://(?:[^.]+\.)?elpais\.com/.*/(?:[^` +
			`/#?]+)\.html(?:$|[?#]))|(?:https?://(?:www\.)?engadget\.com/video/(?:[^/?#]+))|(` +
			`?:https?://ec\.europa\.eu/avservices/(?:video/player|audio/audioDetails)\.cfm\?.` +
			`*?\bref=(?:[A-Za-z0-9-]+))|(?:https?://(?:www\.)?extremetube\.com/(?:[^/]+/)?vid` +
			`eo/(?:[^/#?&]+))|(?:(?:https?://(?:[\w-]+\.)?(?:facebook\.com|facebookcorewwwi\.` +
			`onion)/(?:[^#]*?\#!/)?(?:(?:video/video\.php|photo\.php|video\.php|video/embed|s` +
			`tory\.php)\?(?:.*?)(?:v|video_id|story_fbid)=|[^/]+/videos/(?:[^/]+/)?|[^/]+/pos` +
			`ts/|groups/[^/]+/permalink/)|facebook:)(?:[0-9]+))|(?:https?://(?:[\w-]+\.)?face` +
			`book\.com/plugins/video\.php\?.*?\bhref=(?:https.+))|(?:https?://(?:www\.)?faz\.` +
			`net/(?:[^/]+/)*.*?-(?:\d+)\.html)|(?:(?:5min:|https?://(?:[^/]*?5min\.com/|deliv` +
			`ery\.vidible\.tv/aol)(?:(?:Scripts/PlayerSeed\.js|playerseed/?)?\?.*?playList=)?` +
			`)(?:\d+))|(?:http://(?:www\.)?5-tv\.ru/(?:(?:[^/]+/)+(?:\d+)|(?:[^/?#]+)(?:[/?#]` +
			`)?))|(?:https?://(?:www\.|secure\.)?flickr\.com/photos/[\w\-_@]+/(?:\d+))|(?:htt` +
			`ps?://(?:www\.)?formula1\.com/(?:content/fom-website/)?en/video/\d{4}/\d{1,2}/(?` +
			`:.+?)\.html)|(?:https?://(?:video\.(?:insider\.)?fox(?:news|business)\.com)/v/(?` +
			`:video-embed\.html\?video_id=)?(?:\d+))|(?:https?://(?:www\.)?(?:insider\.)?foxn` +
			`ews\.com/(?!v)([^/]+/)+(?:[a-z-]+))|(?:https?://(?:www\.)?franceculture\.fr/emis` +
			`sions/(?:[^/]+/)*(?:[^/?#&]+))|(?:https?://(?:www\.)?freesound\.org/people/[^/]+` +
			`/sounds/(?:[^/]+))|(?:https?://(?:www\.)?gamespot\.com/(?:video|article|review)s` +
			`/(?:[^/]+/\d+-|embed/)(?:\d+))|(?:https?://(?:www\.)?gaskrank\.tv/tv/(?:[^/]+)/(` +
			`?:[^/]+)\.htm)|(?:https?://(?:www\.)?gdcvault\.com/play/(?:\d+)/(?:(\w|-)+)?)|(?` +
			`:https?://(?:www\.)?gfycat\.com/(?:ifr/|gifs/detail/)?(?:[^/?#]+))|(?:https?://(` +
			`?:www\.)?godtube\.com/watch/\?v=(?:[\da-zA-Z]+))|(?:^https?://video\.golem\.de/.` +
			`+?/(?:.+?)/)|(?:https?://on-demand\.gputechconf\.com/gtc/2015/video/S(?:\d+)\.ht` +
			`ml)|(?:https?://(?:www\.)?historicfilms\.com/(?:tapes/|play)(?:\d+))|(?:https?:/` +
			`/(?:www\.)?hitrecord\.org/records/(?:\d+))|(?:http?://(?:www\.)?hornbunny\.com/v` +
			`ideos/(?:[a-z-]+)-(?:\d+)\.html)|(?:https?://[\da-z-]+\.(?:howstuffworks|stuff(?` +
			`:(?:youshould|theydontwantyouto)know|toblowyourmind|momnevertoldyou)|(?:brain|ca` +
			`r)stuffshow|fwthinking|geniusstuff)\.com/(?:[^/]+/)*(?:\d+-)?(?:.+?)-video\.htm)` +
			`|(?:https?://.+?\.ign\.com/(?:[^/]+/)?(?:videos|show_videos|articles|feature|(?:` +
			`[^/]+/\d+/video))(/.+)?/(?:.+))|(?:https?://(?:www\.)?pcmag\.com/(?:videos|artic` +
			`le2)(/.+)?/(?:.+))|(?:https?://(?:www|m)\.imdb\.com/(?:video|title|list).+?[/-]v` +
			`i(?:\d+))|(?:https?://(?:i\.)?imgur\.com/(?!(?:a|gallery|(?:t(?:opic)?|r)/[^/]+)` +
			`/)(?:[a-zA-Z0-9]+))|(?:https?://(?:i\.)?imgur\.com/(?:gallery|(?:t(?:opic)?|r)/[` +
			`^/]+)/(?:[a-zA-Z0-9]+))|(?:https?://(?:www\.)?ina\.fr/video/(?:I?[A-Z0-9]+))|(?:` +
			`https?://(?:www\.)?infoq\.com/(?:[^/]+/)+(?:[^/]+))|(?:(?:https?://(?:www\.)?ins` +
			`tagram\.com/p/(?:[^/?#&]+)))|(?:https?://(?:www\.)?90tv\.ir/video/(?:[0-9]+)/.*)` +
			`|(?:https?://(?:www\.)?ivideon\.com/tv/(?:[^/]+/)*camera/(?:\d+-[\da-f]+)/(?:\d+` +
			`))|(?:https?://(?:(?:www|m)\.)?izlesene\.com/(?:video|embedplayer)/(?:[^/]+/)?(?` +
			`:[0-9]+))|(?:https?://(?:licensing\.jamendo\.com/[^/]+|(?:www\.)?jamendo\.com)/t` +
			`rack/(?:[0-9]+)/(?:[^/?#&]+))|(?:https?://.*?\.jeuxvideo\.com/.*/(.*?)\.htm)|(?:` +
			`(?:joj:|https?://media\.joj\.sk/embed/)(?:[^/?#^]+))|(?:(?:https?://content\.jwp` +
			`latform\.com/(?:feeds|players|jw6)/|jwplatform:)(?:[a-zA-Z0-9]{8}))|(?:https?://` +
			`(?:www\.)?keezmovies\.com/video/(?:(?:[^/]+)-)?(?:\d+))|(?:https?://(?:www\.)?ki` +
			`ckstarter\.com/projects/(?:[^/]*)/.*)|(?:https?://krasview\.ru/(?:video|embed)/(` +
			`?:\d+))|(?:https?://(?:www\.)?loc\.gov/(?:item/|today/cyberlc/feature_wdesc\.php` +
			`\?.*\brec=)(?:[0-9a-z_.]+))|(?:(?:limelight:media:|https?://(?:link\.videoplatfo` +
			`rm\.limelight\.com/media/|assets\.delvenetworks\.com/player/loader\.swf)\?.*?\bm` +
			`ediaId=)(?:[a-z0-9]{32}))|(?:https?://(?:new\.)?livestream\.com/(?:accounts/(?:\` +
			`d+)|(?:[^/]+))/(?:events/(?:\d+)|(?:[^/]+))(?:/videos/(?:\d+))?)|(?:https?://(?:` +
			`www\.)?lovehomeporn\.com/video/(?:\d+)(?:/(?:[^/?#&]+))?)|(?:https?://(?:www\.)?` +
			`macgamestore\.com/mediaviewer\.php\?trailer=(?:\d+))|(?:(?i)https?://(?:www\.)?m` +
			`anyvids\.com/video/(?:\d+))|(?:https?://(?:www\.)?massengeschmack\.tv/play/(?:[^` +
			`?&#]+))|(?:https://player\.megaphone\.fm/(?:[A-Z0-9]+))|(?:https?://(?:www\.)?me` +
			`tacafe\.com/watch/(?:[^/]+)/(?:[^/?#]+))|(?:https?://(?:www\.)?metacritic\.com/.` +
			`+?/trailers/(?:\d+))|(?:(?:mva:|https?://(?:mva\.microsoft|(?:www\.)?microsoftvi` +
			`rtualacademy)\.com/[^/]+/training-courses/[^/?#&]+-)(?:\d+)(?::|\?l=)(?:[\da-zA-` +
			`Z]+_\d+))|(?:https?://(?:[\da-z_-]+\.)*(?:mlb)\.com/(?:(?:(?:[^/]+/)*c-|(?:share` +
			`d/video/embed/(?:embed|m-internal-embed)\.html|(?:[^/]+/)+(?:play|index)\.jsp|)\` +
			`?.*?\bcontent_id=)(?:\d+)))|(?:https?://(?:www\.)?mofosex\.com/videos/(?:\d+)/(?` +
			`:[^/?#&.]+)\.html)|(?:https?://(?:www\.)?mojvideo\.com/video-(?:[^/]+)/(?:[a-f0-` +
			`9]+))|(?:(?:https?://(?:www\.)?myvi\.(?:(?:ru/player|tv)/(?:(?:embed/html|flash|` +
			`api/Video/Get)/|content/preloader\.swf\?.*\bid=)|ru/watch/)|myvi:)(?:[\da-zA-Z_-` +
			`]+))|(?:https?://(?:watch\.|www\.)?nba\.com/(?:(?:[^/]+/)+(?:[^?]*?))/?(?:/index` +
			`\.html)?(?:\?.*)?$)|(?:https?://(?:www\.)?ndr\.de/(?:[^/]+/)*(?:[^/?#]+),[\da-z]` +
			`+\.html)|(?:https?://(?:www\.)?ndr\.de/(?:[^/]+/)*(?:[\da-z]+)-(?:player|externa` +
			`lPlayer)\.html)|(?:https?://(?:www\.)?n-joy\.de/(?:[^/]+/)*(?:[\da-z]+)-(?:playe` +
			`r|externalPlayer)_[^/]+\.html)|(?:https?://(?:[^/]+\.)?ndtv\.com/(?:[^/]+/)*vide` +
			`os?/?(?:[^/]+/)*[^/?^&]+-(?:\d+))|(?:https?://(?:www\.)?netzkino\.de/\#!/(?:[^/]` +
			`+)/(?:[^/]+))|(?:https?://(?:www\.)?newgrounds\.com/(?:audio/listen|portal/view)` +
			`/(?:[0-9]+))|(?:https?://hk\.dv\.nextmedia\.com/actionnews/[^/]+/(?:\d+)/(?:\d+)` +
			`/\d+)|(?:(?:https?://api\.nexx(?:\.cloud|cdn\.com)/v3/(?:\d+)/videos/byid/|nexx:` +
			`(?:(?:\d+):)?|https?://arc\.nexx\.cloud/api/video/)(?:\d+))|(?:https?://(?:www\.` +
			`)?(?:nhl|wch2016)\.com/(?:[^/]+/)*c-(?:\d+))|(?:https?://media\.cms\.nova\.cz/em` +
			`bed/(?:[^/?#&]+))|(?:https?://(?:(?:www|cn)\.)?nowness\.com/(?:story|(?:series|c` +
			`ategory)/[^/]+)/(?:[^/]+?)(?:$|[?#]))|(?:https?://(?:www\.)?ntv\.ru/(?:[^/]+/)*(` +
			`?:[^/?#&]+))|(?:https?://(?:(?:www|m|mobile)\.)?(?:odnoklassniki|ok)\.ru/(?:vide` +
			`o(?:embed)?/|web-api/video/moviePlayer/|live/|dk\?.*?st\.mvId=)(?:[\d-]+))|(?:(?` +
			`:ooyala:|https?://.+?\.ooyala\.com/.*?(?:embedCode|ec)=)(?:.+?)(&|$))|(?:https?:` +
			`//(?:(?:www\.)?packtpub\.com/mapt|subscription\.packtpub\.com)/video/[^/]+/(?:\d` +
			`+)/(?:\d+)/(?:\d+))|(?:https?://(?:(?:www\.)?pandora\.tv/view/(?:[^/]+)/(?:\d+)|` +
			`(?:.+?\.)?channel\.pandora\.tv/channel/video\.ptv\?|m\.pandora\.tv/?\?))|(?:http` +
			`s?://(?:www\.)?patreon\.com/(?:creation\?hid=|posts/(?:[\w-]+-)?)(?:\d+))|(?:htt` +
			`ps?://(?:www\.)?pearvideo\.com/video_(?:\d+))|(?:https?://(?:www\.)?people\.com/` +
			`people/videos/0,,(?:\d+),00\.html)|(?:https?://(?:[a-z0-9]+\.)?photobucket\.com/` +
			`.*(([\?\&]current=)|_)(?:.*)\.(?:(flv)|(mp4)))|(?:https?://(?:www\.)?play\.fm/(?` +
			`:(?:[^/]+/)+(?:[^/]+))/?(?:$|[?#]))|(?:https?://(?:www\.)?plays\.tv/(?:video|emb` +
			`eds)/(?:[0-9a-f]{18}))|(?:https?://(?:www\.)?playvid\.com/watch(\?v=|/)(?:.+?)(?` +
			`:#|$))|(?:(?:https?)://(?:(?:[^.]+)\.podomatic\.com/entry|(?:www\.)?podomatic\.c` +
			`om/podcasts/(?:[^/]+)/episodes)/(?:[^/?#&]+))|(?:https?://(?:www\.)?pokemon\.com` +
			`/[a-z]{2}(?:.*?play=(?:[a-z0-9]{32})|/(?:[^/]+/)+(?:[^/?#&]+)))|(?:(?:https?://)` +
			`(?:www\.|)91porn\.com/.+?\?viewkey=(?:[\w\d]+))|(?:https?://(?:[a-zA-Z]+\.)?porn` +
			`\.com/videos/(?:(?:[^/]+)-)?(?:\d+))|(?:https?://(?:www\.)?pornhd\.com/(?:[a-z]{` +
			`2,4}/)?videos/(?:\d+)(?:/(?:.+))?)|(?:https?://(?:\w+\.)?pornotube\.com/(?:[^?#]` +
			`*?)/video/(?:[0-9]+))|(?:https?://(?:www\.)?puhutv\.com/(?:[^/?#&]+)-izle)|(?:ht` +
			`tps?://(?:www\.)?presstv\.ir/[^/]+/(?:\d+)/(?:\d+)/(?:\d+)/(?:\d+)/(?:[^/]+)?)|(` +
			`?:https?://(?:.+?)\.(?:radio\.(?:de|at|fr|pt|es|pl|it)|rad\.io))|(?:https?://(?:` +
			`www\.)?radiojavan\.com/videos/video/(?:[^/]+)/?)|(?:https?://[^/]+\.(?:rai\.(?:i` +
			`t|tv)|rainews\.it)/dl/.+?-(?:[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]` +
			`{12})(?:-.+?)?\.html)|(?:https?://(?:videos\.raywenderlich\.com/courses|(?:www\.` +
			`)?raywenderlich\.com)/(?:[^/]+)/lessons/(?:\d+))|(?:https?://(?:www\.)?(?:rbmara` +
			`dio|redbullradio)\.com/shows/(?:[^/]+)/episodes/(?:[^/?#&]+))|(?:https?://(?:(?:` +
			`www\.)?redtube\.com/|embed\.redtube\.com/\?.*?\bid=)(?:[0-9]+))|(?:(?:rentv:|htt` +
			`ps?://(?:www\.)?ren\.tv/(?:player|video/epizod)/)(?:\d+))|(?:^https?://(?:www\.)` +
			`?reverbnation\.com/.*?/song/(?:\d+).*?$)|(?:https?://(?:www\.)?rockstargames\.co` +
			`m/videos(?:/video/|#?/?\?.*\bvideo=)(?:\d+))|(?:https?://(?:www\.)?prehravac\.ro` +
			`zhlas\.cz/audio/(?:[0-9]+))|(?:rts:(?:\d+)|https?://(?:.+?\.)?rts\.ch/(?:[^/]+/)` +
			`{2,}(?:[0-9]+)-(?:.+?)\.html)|(?:https?://(?:www\.)?rtvs\.sk/(?:radio|televizia)` +
			`/archiv/\d+/(?:\d+))|(?:https?://(?:test)?player\.(?:rutv\.ru|vgtrk\.com)/(?:fla` +
			`sh\d+v/container\.swf\?id=|iframe/(?:swf|video|live)/id/|index/iframe/cast_id/)(` +
			`?:\d+))|(?:https?://(?:(?:v2|www)\.)?videos\.sapo\.(?:pt|cv|ao|mz|tl)/(?:[\da-zA` +
			`-Z]{20}))|(?:https?://(?:www\.)?screencast\.com/t/(?:[a-zA-Z0-9]+))|(?:https?://` +
			`(?:www\.)?senate\.gov/isvp/?\?(?:.+))|(?:https?://(?:www\.)?seznamzpravy\.cz/ifr` +
			`ame/player\?.*\bsrc=)|(?:https?://vivo\.sx/(?:[\da-z]{10}))|(?:https?://(?:www\.` +
			`)?skysports\.com/watch/video/(?:[0-9]+))|(?:https?://(?:www\.)?slideshare\.net/[` +
			`^/]+?/(?:.+?)($|\?))|(?:https?://(?:\w+\.)?slutload\.com/(?:video/[^/]+|embed_pl` +
			`ayer|watch)/(?:[^/]+))|(?:https?://(?:www\.)?soundgasm\.net/u/(?:[0-9a-zA-Z_-]+)` +
			`/(?:[0-9a-zA-Z_-]+))|(?:https?://(?:(?:www|m|[a-z]{2})\.)?spankbang\.com/(?:[\da` +
			`-z]+)/video)|(?:https?://(?:www\.)?stitcher\.com/podcast/(?:[^/]+/)+e/(?:(?:[^/#` +
			`?&]+?)-)?(?:\d+)(?:[/#?&]|$))|(?:https?://sportdeutschland\.tv/(?:[^/?#]+)/(?:[^` +
			`?#/]+)(?:$|[?#]))|(?:https?://(?:(?:www|play)\.)?(?:srf|rts|rsi|rtr|swissinfo)\.` +
			`ch/play/(?:tv|radio)/[^/]+/(?:video|audio)/[^?]+\?id=(?:[0-9a-f\-]{36}|\d+))|(?:` +
			`https?://openclassroom\.stanford\.edu(?:/?|(/MainFolder/(?:HomePage|CoursePage|V` +
			`ideoPage)\.php([?]course=(?:[^&]+)(&video=(?:[^&]+))?(&.*)?)?))$)|(?:https?://st` +
			`reamable\.com/(?:[es]/)?(?:\w+))|(?:https?://(?:(?:www\.)?sunporno\.com/videos|e` +
			`mbeds\.sunporno\.com/embed)/(?:\d+))|(?:https?://(?:www\.)?swrmediathek\.de/(?:c` +
			`ontent/)?player\.htm\?show=(?:[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f` +
			`]{12}))|(?:https?://(?:www\.)?tagesschau\.de/(?:[^/]+/(?:[^/]+/)*?(?:[^/#?]+?(?:` +
			`-?[0-9]+)?))(?:~_?[^/#?]+?)?\.html)|(?:https?://(?:www\.)?tastytrade\.com/tt/sho` +
			`ws/[^/]+/episodes/(?:[^/?#&]+))|(?:https?://tds\.lifeway\.com/v1/trainingdeliver` +
			`ysystem/courses/(?:\d+)/index\.html)|(?:https?://(?:www\.)?teachertube\.com/(vie` +
			`wVideo\.php\?video_id=|music\.php\?music_id=|video/(?:[\da-z-]+-)?|audio/)(?:\d+` +
			`))|(?:(?:https?://)(?:www|embed(?:-ssl)?)(?:\.ted\.com/((?:playlists(?:/\d+)?)|(` +
			`(?:talks))|(?:watch)/[^/]+/[^/]+)(/lang/(.*?))?/(?:[\w-]+).*)$)|(?:^https?://(?:` +
			`www\.)?t13\.cl/videos(?:/[^/]+)+/(?:[\w-]+))|(?:https?://(?:www\.)?tenta\.com/ho` +
			`w-to-download-videos)|(?:https?://(?:www\.)?thisoldhouse\.com/(?:watch|how-to|tv` +
			`-episode)/(?:[^/?#]+))|(?:https?://(?:m\.)?tiktok\.com/v/(?:\d+))|(?:https?://pl` +
			`ayer\.(?:tna|emp)flix\.com/video/(?:\d+))|(?:https?://(?:www\.)?tnaflix\.com/[^/` +
			`]+/(?:[^/]+)/video(?:\d+))|(?:https?://(?:www\.)?empflix\.com/(?:videos/(?:.+?)-` +
			`|[^/]+/(?:[^/]+)/video)(?:[0-9]+))|(?:https?://(?:www\.)?moviefap\.com/videos/(?` +
			`:[0-9a-f]+)/(?:[^/]+)\.html)|(?:https?://videos\.toypics\.net/view/(?:[0-9]+))|(` +
			`?:https?://(?:(?:www|m)\.)?trilulilu\.ro/(?:[^/]+/)?(?:[^/#\?]+))|(?:https?://(?` +
			`:www\.)?tube8\.com/(?:[^/]+/)+(?:[^/]+)/(?:\d+))|(?:https?://(?:[^/?#&]+)\.tumbl` +
			`r\.com/(?:post|video)/(?:[0-9]+)(?:$|[/?#]))|(?:https?://(?:www\.)?tunein\.com/s` +
			`tation/.*?audioClipId\=(?:\d+))|(?:https?://(?:www\.)?tunein\.com/(?:radio/.*?-s` +
			`|station/.*?StationId=|embed/player/s)(?:\d+))|(?:https?://(?:www\.)?tunein\.com` +
			`/(?:radio/.*?-p|program/.*?ProgramId=|embed/player/p)(?:\d+))|(?:https?://tun\.i` +
			`n/(?:[A-Za-z0-9]+))|(?:https?://(?:www\.)?tvanouvelles\.ca/videos/(?:\d+))|(?:ht` +
			`tps?://(?:www\.)?tvc\.ru/video/iframe/id/(?:\d+))|(?:https?://(?:www\.)?tvc\.ru/` +
			`(?!video/iframe/id/)(?:[^?#]+))|(?:https?://(?:(?:[^/]+)\.)?tvn24(?:bis)?\.pl/(?` +
			`:[^/]+/)*(?:[^/]+))|(?:https?://(?:www\.)?tvnoe\.cz/video/(?:[0-9]+))|(?:https?:` +
			`//[^/]+\.tvp\.(?:pl|info)/(?:video/(?:[^,\s]*,)*|(?:(?!\d+/)[^/]+/)*)(?:\d+))|(?` +
			`:https?://tvplay\.(?:tv3\.lt|skaties\.lv|tv3\.ee)/[^/]+/[^/?#&]+-(?:\d+))|(?:htt` +
			`ps?://(?:www\.)?20min\.ch/(?:videotv/*\?.*?\bvid=|videoplayer/videoplayer\.html\` +
			`?.*?\bvideoId@)(?:\d+))|(?:https?://(?:clips\.twitch\.tv/(?:[^/]+/)*|(?:www\.)?t` +
			`witch\.tv/[^/]+/clip/)(?:[^/?#&]+))|(?:https?://amp\.twimg\.com/v/(?:[0-9a-f\-]{` +
			`36}))|(?:https?://video\.udn\.com/(?:embed|play)/news/(?:\d+))|(?:https?://(?:ww` +
			`w\.)?(?:digiteka\.net|ultimedia\.com)/(?:deliver/(?:generic|musique)(?:/[^/]+)*/` +
			`(?:src|article)|default/index/video(?:generic|music)/id)/(?:[\d+a-z]+))|(?:https` +
			`?://utv\.unistra\.fr/(?:index|video)\.php\?id_video\=(?:\d+))|(?:https?://(?:.+?` +
			`\.)?uol\.com\.br/.*?(?:(?:mediaId|v)=|view/(?:[a-z0-9]+/)?|video(?:=|/(?:\d{4}/\` +
			`d{2}/\d{2}/)?))(?:\d+|[\w-]+-[A-Z0-9]+))|(?:https?://(?:www\.)?usatoday\.com/(?:` +
			`[^/]+/)*(?:[^?/#]+))|(?:https?://(?:(?:app|embed)\.)?ustudio\.com/embed/(?:[^/]+` +
			`)/(?:[^/]+))|(?:https?://(?:www\.)?video\.varzesh3\.com/(?:[^/]+/)+(?:[^/]+)/?)|` +
			`(?:https?://(?:[^/]+\.)?vbox7\.com/(?:play:|(?:emb/external\.php|player/ext\.swf` +
			`)\?.*?\bvid=)(?:[\da-fA-F]+))|(?:https?://veehd\.com/video/(?:\d+))|(?:https?://` +
			`(?:.+?\.)?vesti\.ru/(?:.+))|(?:(?:https?://(?:www\.)?vevo\.com/watch/(?!playlist` +
			`|genre)(?:[^/]+/(?:[^/]+/)?)?|https?://cache\.vevo\.com/m/html/embed\.html\?vide` +
			`o=|https?://videoplayer\.vevo\.com/embed/embedded\?videoId=|vevo:)(?:[^&?#]+))|(` +
			`?:(?:https?://(?:www\.)?(?:vgtv.no|bt.no/tv|aftenbladet.no/tv|fvn.no/fvntv|aften` +
			`posten.no/webtv|ap.vgtv.no/webtv|tv.aftonbladet.se/abtv|www.aftonbladet.se/tv)/?` +
			`(?:(?:\#!/)?(?:video|live)/|embed?.*id=|a(?:rticles)?/)|(?:vgtv|bttv|satv|fvntv|` +
			`aptv|abtv):)(?:\d+))|(?:https?://(?:www\.)?viddler\.com/(?:v|embed|player)/(?:[a` +
			`-z0-9]+))|(?:https?://videopress\.com/embed/(?:[\da-zA-Z]+))|(?:https?://(?:www\` +
			`.|m\.|)videosz\.com/[a-z]+/[a-z]+/(?:[0-9]+)_)|(?:https?://(?:www\.)?vidlii\.com` +
			`/(?:watch|embed)\?.*?\bv=(?:[0-9A-Za-z_-]{11}))|(?:https?://(?:(?:www|(?:player)` +
			`)\.)?vimeo(?:pro)?\.com/(?!(?:channels|album)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|` +
			`ondemand/)(?:.*?/)?(?:(?:play_redirect_hls|moogaloop\.swf)\?clip_id=)?(?:videos?` +
			`/)?(?:[0-9]+)(?:/[\da-f]+)?/?(?:[?&].*)?(?:[#].*)?$)|(?:https?://(?:www\.)?vimeo` +
			`\.com/ondemand/(?:[^/?#&]+))|(?:https://vimeo\.com/[^/]+/review/(?:[^/]+))|(?:ht` +
			`tps?://(?:player\.vimple\.(?:ru|co)/iframe|vimple\.(?:ru|co))/(?:[\da-f-]{32,36}` +
			`))|(?:https?://(?:www\.)?vine\.co/(?:v|oembed)/(?:\w+))|(?:(?:viqeo:|https?://cd` +
			`n\.viqeo\.tv/embed/*\?.*?\bvid=|https?://api\.viqeo\.tv/v\d+/data/startup?.*?\bv` +
			`ideo(?:%5B%5D|\[\])=)(?:[\da-f]+))|(?:https?://(?:(?:(?:(?:m|new)\.)?vk\.com/vid` +
			`eo_|(?:www\.)?daxab.com/)ext\.php\?(?:.*?\boid=(?:-?\d+).*?\bid=(?:\d+).*)|(?:(?` +
			`:(?:m|new)\.)?vk\.com/(?:.+?\?.*?z=)?video|(?:www\.)?daxab.com/embed/)(?:-?\d+_\` +
			`d+)(?:.*\blist=(?:[\da-f]+))?))|(?:https?://(?:(?:www|m)\.)?vlive\.tv/video/(?:[` +
			`0-9]+))|(?:https?://(?:m\.)?vuclip\.com/w\?.*?cid=(?:[0-9]+))|(?:https?://(?:(?:` +
			`www|view)\.)?vzaar\.com/(?:videos/)?(?:\d+))|(?:(?:washingtonpost:|https?://(?:w` +
			`ww\.)?washingtonpost\.com/video/(?:[^/]+/)*)(?:[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-` +
			`[\da-f]{4}-[\da-f]{12}))|(?:(?:wat:|https?://(?:www\.)?wat\.tv/video/.*-)(?:[0-9` +
			`a-z]+))|(?:https?://m\.weibo\.cn/status/(?:[0-9]+)(\?.+)?)|(?:https?://(?:www|m)` +
			`\.worldstar(?:candy|hiphop)\.com/(?:videos|android)/video\.php\?.*?\bv=(?:[^&]+)` +
			`)|(?:https?://(?:.+?\.)?xhamster\.com/(?:movies/(?:\d+)/(?:[^/]*)\.html|videos/(` +
			`?:[^/]*)-(?:\d+)))|(?:https?://(?:.+?\.)?xhamster\.com/xembed\.php\?video=(?:\d+` +
			`))|(?:https?://(?:video|www)\.xnxx\.com/video-?(?:[0-9a-z]+)/)|(?:(?:xtube:|http` +
			`s?://(?:www\.)?xtube\.com/(?:watch\.php\?.*\bv=|video-watch/(?:embedded/)?(?:[^/` +
			`]+)-))(?:[^/?&#]+))|(?:https?://(?:(?:www\.)?xvideos\.com/video|flashservice\.xv` +
			`ideos\.com/embedframe/|static-hw\.xvideos\.com/swf/xv-player\.swf\?.*?\bid_video` +
			`=)(?:[0-9]+))|(?:https?://(?:www\.)?xxxymovies\.com/videos/(?:\d+)/(?:[^/]+))|(?` +
			`:https?://v\.yinyuetai\.com/video(?:/h5)?/(?:[0-9]+))|(?:https?://(?:\w+\.)?youj` +
			`izz\.com/videos/(?:[^/#?]*-(?:\d+)\.html|embed/(?:\d+)))|(?:https?://(?:www\.)?y` +
			`ouporn\.com/watch/(?:\d+)/(?:[^/?#&]+))|(?:https?://(?:www\.)?yourporn\.sexy/pos` +
			`t/(?:[^/?#&.]+))|(?:https?://(?:www\.)?(?:yourupload\.com/(?:watch|embed)|embed\` +
			`.yourupload\.com)/(?:[A-Za-z0-9]+))|(?:^((?:https?://|//)(?:(?:(?:(?:\w+\.)?[yY]` +
			`[oO][uU][tT][uU][bB][eE](?:-nocookie)?\.com/|(?:www\.)?deturl\.com/www\.youtube\` +
			`.com/|(?:www\.)?pwnyoutube\.com/|(?:www\.)?hooktube\.com/|(?:www\.)?yourepeat\.c` +
			`om/|tube\.majestyc\.net/|(?:www\.)?invidio\.us/|youtube\.googleapis\.com/)(?:.*?` +
			`\#/)?(?:(?:(?:v|embed|e)/(?!videoseries))|(?:(?:(?:watch|movie)(?:_popup)?(?:\.p` +
			`hp)?/?)?(?:\?|\#!?)(?:.*?[&;])??v=)))|(?:youtu\.be|vid\.plus|zwearz\.com/watch|)` +
			`/|(?:www\.)?cleanvideosearch\.com/media/action/yt/watch\?videoId=))?([0-9A-Za-z_` +
			`-]{11})(?!.*?\blist=(?:(?:PL|LL|EC|UU|FL|RD|UL|TL)[0-9A-Za-z-_]{10,}|WL))$)`,
	}
}
